#!/usr/bin/env python3
"""Append CJ-MLK-04 Cycle 4 CVS claims to evidence register."""
import csv
import os

REGISTER = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"
TODAY = "2026-08-07"

claims = [
    # PIR-12: Post-break PN Melaka status
    {
        "claim_id": "CVS-MLK-275",
        "workstream": "CJ-MLK-04",
        "claim": "PAS officially terminated political cooperation with BERSATU on 8 June 2026 per decision of PAS Central Working Committee special meeting endorsed by Majlis Syura Ulamak 2 Jun 2026; effective immediately; ending the PN coalition two-party foundation",
        "source_name": "berita.pas.org.my (official PAS media) + Harakah Daily",
        "source_type": "L4",
        "source_url": "https://berita.pas.org.my/2026/06/08/kenyataan-media-pas-pusat-kerjasama-politik-pas-bersatu/",
        "source_date": "2026-06-08",
        "evidence_type": "Official party statement",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "2", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "Impact on PN Melaka structure (14 May appointees) not yet clarified",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor post-break PN Melaka operational status",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-276",
        "workstream": "CJ-MLK-04",
        "claim": "PAS announced intention to contest 16 of Melaka 28 state seats including N02 Tanjung Bidara held by CM Ab Rauf Yusoh; up from 9 seats in pre-break PN allocation",
        "source_name": "FMT + 1media.my",
        "source_type": "L4",
        "source_url": "https://www.freemalaysiatoday.com/category/nation/2026/08/04/will-pas-be-as-generous-with-seats-in-melaka",
        "source_date": "2026-08-04",
        "evidence_type": "Media report + party announcement",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "Final seat allocation subject to BN-PN negotiations",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor BN-PN seat negotiation outcomes",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-277",
        "workstream": "CJ-MLK-04",
        "claim": "Zulkifli Ismail as PAS Melaka Commissioner expressed hope PAS would govern Melaka by PAS 70th anniversary (2027); PAS currently 69 years old founded 1957 in Masjid Tanah Melaka",
        "source_name": "Harakah Daily",
        "source_type": "L4",
        "source_url": "https://harakahdaily.net/2026/04/26/pas-sasar-kuasai-melaka-menjelang-usia-70-tahun/",
        "source_date": "2026-04-26",
        "evidence_type": "Party leader statement",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "1", "completeness": "1",
        "issue_gap": "Full article restricted; introductory content only",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-278",
        "workstream": "CJ-MLK-04",
        "claim": "Melaka hosted central PAS Hari Raya open house for first time since PAS founded in Masjid Tanah Melaka 1957; organized by Zulkifli Ismail at D Village Resort Ayer Keroh",
        "source_name": "Harakah Daily",
        "source_type": "L4",
        "source_url": "https://harakahdaily.net/2026/04/11/melaka-julung-kali-tuan-rumah-rumah-terbuka-pas-pusat/",
        "source_date": "2026-04-11",
        "evidence_type": "Event report",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "None",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-279",
        "workstream": "CJ-MLK-04",
        "claim": "[ASSESSMENT] Post-break PN Melaka structure (14 May 2026) is fundamentally disrupted — Chairman Radzi Jidin and Election Director Ali Mohamad are BERSATU (party PAS severed ties with 8 Jun 2026); Deputy Zulkifli and Secretary Bakri are PAS; structure viability uncertain",
        "source_name": "Analysis based on berita.pas.org.my + FMT",
        "source_type": "L4",
        "source_url": "https://berita.pas.org.my/2026/06/08/kenyataan-media-pas-pusat-kerjasama-politik-pas-bersatu/",
        "source_date": "2026-06-08",
        "evidence_type": "Analytical assessment",
        "tier": "T3",
        "validation_status": "Inferred",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "0",
        "issue_gap": "No post-break PN Melaka meeting or restructuring announcement found",
        "owner": "CJ-MLK-04",
        "action_required": "Search for post-break PN Melaka statements or new structure",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-280",
        "workstream": "CJ-MLK-04",
        "claim": "Analyst Yusri Ibrahim (Ilham Centre): In Melaka PN is stronger than BN based on GE15 — PN won 3 parliamentary seats (PAS Tangga Batu+Jasin, Bersatu Masjid Tanah), BN 0; if parliamentary votes broken down by state constituencies PN leads 10-4",
        "source_name": "FMT (citing Ilham Centre Yusri Ibrahim)",
        "source_type": "L4",
        "source_url": "https://www.freemalaysiatoday.com/category/nation/2026/08/04/will-pas-be-as-generous-with-seats-in-melaka",
        "source_date": "2026-08-04",
        "evidence_type": "Analyst assessment",
        "tier": "T3",
        "validation_status": "Inferred",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "Analyst opinion not independently verified",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-281",
        "workstream": "CJ-MLK-04",
        "claim": "BN-PN cooperation for Melaka PRN being discussed — Hadi Awang says different type of understanding possible (3 Aug 2026); Ab Rauf says BN Plus formula open but depends on party strengths (3 Aug 2026)",
        "source_name": "FMT",
        "source_type": "L4",
        "source_url": "https://www.freemalaysiatoday.com/category/nation/2026/08/04/will-pas-be-as-generous-with-seats-in-melaka",
        "source_date": "2026-08-04",
        "evidence_type": "Media report of leader statements",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "No formal BN-PN agreement announced yet",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor for formal BN-PN Melaka cooperation announcement",
        "last_reviewed": TODAY,
    },
    # PIR-13: Helmy enrichment
    {
        "claim_id": "CVS-MLK-282",
        "workstream": "CJ-MLK-04",
        "claim": "Mohd Noor Helmy is AJK (Executive Committee Member) for UMNO Kota Melaka division and former Ketua Pemuda UMNO Kota Melaka; born 8 Jan 1981 Negeri Sembilan; BEng UiTM MBA Asia e University",
        "source_name": "Wikipedia EN + MS",
        "source_type": "L4",
        "source_url": "https://en.wikipedia.org/wiki/Mohd_Noor_Helmy_Abdul_Halem",
        "source_date": "2026-08-07",
        "evidence_type": "Encyclopedia profile",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "Wikipedia may lag real-time changes",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-283",
        "workstream": "CJ-MLK-04",
        "claim": "Mohd Noor Helmy has 1.2 million TikTok followers and 32.4 million likes as of June 2025 — exceptional social media reach for a state ADUN; primary grassroots mobilization tool",
        "source_name": "Wikipedia EN + MS",
        "source_type": "L4",
        "source_url": "https://en.wikipedia.org/wiki/Mohd_Noor_Helmy_Abdul_Halem",
        "source_date": "2025-06-01",
        "evidence_type": "Social media statistics",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "1", "consistency": "2", "completeness": "1",
        "issue_gap": "Data as of June 2025; may have changed",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-284",
        "workstream": "CJ-MLK-04",
        "claim": "DUN Melaka passed constitution amendment (14 Jul 2026) enabling up to 7 appointed ADUNs; vote 23-5 (23 supported including Opposition Leader Dr Mohd Yadzil, 5 PH rejected); presented by CM Ab Rauf supported by Datuk Rais Yasin; Helmy not named as speaker or debater",
        "source_name": "Astro Awani + The Malaysia Press + The Merdeka Times",
        "source_type": "L4",
        "source_url": "https://www.astroawani.com/berita-politik/dun-melaka-lulus-pindaan-perlembagaan-negeri-berkaitan-adun-lantikan",
        "source_date": "2026-07-14",
        "evidence_type": "Media report of DUN proceedings",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "2", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "Individual voting record not published; Helmy vote inferred from party bloc",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-285",
        "workstream": "CJ-MLK-04",
        "claim": "A Chinese woman Lee Kim Choo 55 moved her IC address to Duyong specifically to vote for Helmy; 50 people changed address at WRUR program; demonstrates cross-community grassroots appeal unusual for UMNO ADUN",
        "source_name": "Malaysiakini (Bernama wire)",
        "source_type": "L4",
        "source_url": "https://www.malaysiakini.com/news/767264",
        "source_date": "2026-02-04",
        "evidence_type": "News report",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "1",
        "issue_gap": "None",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-286",
        "workstream": "CJ-MLK-04",
        "claim": "Helmy 5-year self-assessment (Utusan Mar 2024): I have given my best; philosophy of no false hope; flood issue solved during his term; compatible with CM Ab Rauf corporate style; describes politics as fragile; not aggressively positioning for higher office",
        "source_name": "Utusan Malaysia",
        "source_type": "L4",
        "source_url": "https://www.utusan.com.my/berita/2024/03/lima-tahun-ini-saya-sudah-buat-yang-terbaik/",
        "source_date": "2024-03-08",
        "evidence_type": "Interview",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "1", "consistency": "2", "completeness": "1",
        "issue_gap": "Interview from Mar 2024; views may have evolved",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-287",
        "workstream": "CJ-MLK-04",
        "claim": "Wikipedia PRN Melaka 2026 projects Muhamad Akmal Saleh as potential CM under PN + BN-UMNO coalition; full 28-seat allocation table shows pre-break PN structure with BERSATU in 13 seats PAS in 9 GERAKAN in 5 WAWASAN in 1",
        "source_name": "Wikipedia MS",
        "source_type": "L4",
        "source_url": "https://ms.wikipedia.org/wiki/Pilihan_raya_negeri_Melaka_2026",
        "source_date": "2026-08-07",
        "evidence_type": "Encyclopedia",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "0",
        "issue_gap": "Pre-break allocation; post-break PAS 16-seat plan supersedes BERSATU allocations",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor for updated post-break seat allocation",
        "last_reviewed": TODAY,
    },
    {
        "claim_id": "CVS-MLK-288",
        "workstream": "CJ-MLK-04",
        "claim": "PAS allocated to contest N21 Duyong (Helmy marginal seat 200-vote majority) per Wikipedia PRN Melaka 2026 — Helmy faces PAS challenger in his most vulnerable seat",
        "source_name": "Wikipedia MS PRN Melaka 2026",
        "source_type": "L4",
        "source_url": "https://ms.wikipedia.org/wiki/Pilihan_raya_negeri_Melaka_2026",
        "source_date": "2026-08-07",
        "evidence_type": "Encyclopedia seat allocation",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "1", "completeness": "1",
        "issue_gap": "Pre-break allocation; post-break may change if BN-PAS cooperation agreed",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor whether BN-PAS cooperation leads to Duyong being ceded to BN",
        "last_reviewed": TODAY,
    },
]

# Read existing, append new claims
existing_rows = []
with open(REGISTER, "r", newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        existing_rows.append(row)

# Check for duplicate claim_ids
existing_ids = {r.get("claim_id", "") for r in existing_rows}
new_count = 0
for c in claims:
    if c["claim_id"] not in existing_ids:
        existing_rows.append(c)
        existing_ids.add(c["claim_id"])
        new_count += 1

# Write back
with open(REGISTER, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for row in existing_rows:
        writer.writerow(row)

print(f"Appended {new_count} new CVS claims (CVS-MLK-275 to CVS-MLK-288)")
print(f"Total register entries: {len(existing_rows)}")
