#!/usr/bin/env python3
"""Append CJ-MLK-02 Cycle 4 claims (CVS-MLK-225 to 247) to the CVS Evidence Register."""
import csv
from pathlib import Path

REGISTER = Path("/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv")

FIELDS = [
    "claim_id","workstream","claim","source_name","source_type","source_url",
    "source_date","evidence_type","tier","validation_status","confidence_score",
    "authority","traceability","recency","consistency","completeness",
    "issue_gap","owner","action_required","last_reviewed"
]

# Each claim as a dict. confidence_score is sum of the 5 criteria (each 0-2).
claims = [
    # --- PIR-04: PAC findings + new scrutiny (Astro Awani L4) ---
    {"claim_id":"CVS-MLK-225","workstream":"MLK","claim":"PAC called Ministry of Defence (Mindef) to clarify the Norway missile (peluru berpandu Norway) issue on 11 June 2026 — a PAC summons to MINDEF distinct from the LCS (DR.22/2026) scrutiny, putting MINDEF under PAC scrutiny on at least two procurement matters","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-06-11","evidence_type":"Event/Proceeding","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Headline only; full PAC proceeding record not obtained (parlimen.gov.my PAC page 404)","owner":"CJ-MLK-02","action_required":"Obtain full PAC Norway-missile proceeding record; cross-check with MINDEF response","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-226","workstream":"MLK","claim":"PAC is discussing the need to investigate KWAP's (Kumpulan Wang Amanan Pencen) investment in eFishery (Indonesian aquaculture tech company) as of 16 July 2026 — a new potential PAC probe of pension-fund investment decisions","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-07-16","evidence_type":"Event/Proceeding","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"PAC 'discussing need to investigate' — not yet confirmed as opened probe","owner":"CJ-MLK-02","action_required":"Monitor whether PAC formally opens KWAP/eFishery probe","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-227","workstream":"MLK","claim":"PAC recommends maintaining 70 percent local stake in MAHB (Malaysia Airports Holdings Berhad) to protect national strategic control over airports (1 July 2026) — finding of PAC airports report","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-07-01","evidence_type":"Finding/Recommendation","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Maps to one of 6 PAC 2026 reports; full PDF not extracted","owner":"CJ-MLK-02","action_required":"None; corroborate with L1 PAC PDF if extractable","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-228","workstream":"MLK","claim":"PAC recommends Ministry of Finance (MOF) conduct a comprehensive study to find a more effective government vehicle management model (9 July 2026) — finding of PAC govt-vehicles report","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-07-09","evidence_type":"Finding/Recommendation","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Maps to one of 6 PAC 2026 reports; full PDF not extracted","owner":"CJ-MLK-02","action_required":"None; corroborate with L1 PAC PDF if extractable","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-229","workstream":"MLK","claim":"PAC submitted 17 recommendations to address rising insurance premiums and control private hospital charges (24 June 2026); non-professional component charges by private hospitals identified as main cause of premium hikes (25 June 2026) — finding of PAC health-insurance report","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-06-24","evidence_type":"Finding/Recommendation","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Maps to one of 6 PAC 2026 reports; full PDF not extracted","owner":"CJ-MLK-02","action_required":"None; corroborate with L1 PAC PDF if extractable","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-230","workstream":"MLK","claim":"PAC states FELCRA must seriously comply with statutory requirements (15 July 2026) — finding of PAC FELCRA report","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-07-15","evidence_type":"Finding/Recommendation","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Maps to one of 6 PAC 2026 reports; full PDF not extracted","owner":"CJ-MLK-02","action_required":"None; corroborate with L1 PAC PDF if extractable","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-231","workstream":"MLK","claim":"Mas Ermieyati Samsudin apologised to Asyraf Wajdi and MARA in a defamation suit (saman fitnah) on 6 April 2026 — legal/political context for her trajectory as PAC chair","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-04-06","evidence_type":"Event/Legal","tier":"T2","validation_status":"Partially Verified","confidence_score":6,"authority":1,"traceability":2,"recency":2,"consistency":1,"completeness":0,"issue_gap":"Terms of apology/settlement not detailed","owner":"CJ-MLK-02","action_required":"None; monitoring item for political-standing impact","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-232","workstream":"MLK","claim":"13 Bersatu MPs expressed disappointment with leadership and demanded the party exit PN (10 June 2026); opposition MPs held a meeting without Bersatu (17 June 2026) — BERSATU internal crisis context for Mas Ermieyati's post-suspension trajectory","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=mas%20ermieyati","source_date":"2026-06-10","evidence_type":"Statement/Political","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Mas Ermieyati's personal stance on Bersatu crisis not stated","owner":"CJ-MLK-02","action_required":"Monitor Mas Ermieyati's alignment amid Bersatu crisis","last_reviewed":"2026-08-06"},
    # --- PIR-11: Adam Adli parliamentary + policy (Astro Awani L4) ---
    {"claim_id":"CVS-MLK-233","workstream":"MLK","claim":"Parlimen (Dewan Rakyat): KPT considering construction of a hostel to accommodate 700 TVET students in Betong (29 June 2026) — Adam Adli ministry parliamentary contribution","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=adam%20adli","source_date":"2026-06-29","evidence_type":"Parliamentary/Policy","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Full Hansard text not obtained; parlimen.gov.my pages 404","owner":"CJ-MLK-02","action_required":"Obtain Hansard text if parlimen.gov.my accessible","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-234","workstream":"MLK","claim":"Parlimen (Dewan Rakyat): IPTA admissions based on merit and qualifications, not 'pintu belakang' (backdoor) entry (25 June 2026) — Adam Adli ministry parliamentary contribution defending admissions integrity","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=adam%20adli","source_date":"2026-06-25","evidence_type":"Parliamentary/Policy","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Full Hansard text not obtained","owner":"CJ-MLK-02","action_required":"Obtain Hansard text if parlimen.gov.my accessible","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-235","workstream":"MLK","claim":"IPTs can withdraw student industrial training placements if deemed risky (~5 August 2026) — Adam Adli portfolio policy on industrial-training safety","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=adam%20adli","source_date":"2026-08-05","evidence_type":"Policy","tier":"T2","validation_status":"Partially Verified","confidence_score":6,"authority":1,"traceability":2,"recency":2,"consistency":1,"completeness":0,"issue_gap":"Exact date approximate ('~1 day before collection'); full detail not extracted","owner":"CJ-MLK-02","action_required":"Confirm exact date and full policy text","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-236","workstream":"MLK","claim":"KGB usage guidelines at IPTs showing positive impact on academic integrity (22 July 2026) — Adam Adli portfolio academic-integrity initiative","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=adam%20adli","source_date":"2026-07-22","evidence_type":"Policy","tier":"T2","validation_status":"Partially Verified","confidence_score":6,"authority":1,"traceability":2,"recency":2,"consistency":1,"completeness":0,"issue_gap":"KGB acronym expansion unclear; full guideline detail not extracted","owner":"CJ-MLK-02","action_required":"Clarify KGB acronym and guideline scope","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-237","workstream":"MLK","claim":"Higher Education is driving Malaysia-Africa relations (2 July 2026) — Adam Adli portfolio international-engagement initiative","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=adam%20adli","source_date":"2026-07-02","evidence_type":"Policy/International","tier":"T2","validation_status":"Partially Verified","confidence_score":6,"authority":1,"traceability":2,"recency":2,"consistency":1,"completeness":0,"issue_gap":"Specific bilateral programmes not detailed","owner":"CJ-MLK-02","action_required":"None; monitoring item","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-238","workstream":"MLK","claim":"50000 private tahfiz/pondok graduates eligible for IPTA entry (16 May 2026) — Adam Adli portfolio major higher-ed access initiative","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/search?q=adam%20adli","source_date":"2026-05-16","evidence_type":"Policy","tier":"T2","validation_status":"Partially Verified","confidence_score":6,"authority":1,"traceability":2,"recency":2,"consistency":1,"completeness":0,"issue_gap":"Implementation status not detailed","owner":"CJ-MLK-02","action_required":"None","last_reviewed":"2026-08-06"},
    # --- PIR-04 Wikipedia Mas Ermieyati ---
    {"claim_id":"CVS-MLK-239","workstream":"MLK","claim":"Mas Ermieyati Samsudin is PAC Chairperson since 4 April 2023 (nominated by Anwar Ibrahim, appointed by Johari Abdul), 2nd female PAC chair; MP Masjid Tanah since 2013 (3 terms); BERSATU membership suspended since 2026; Women Chief BERSATU since Oct 2024","source_name":"Wikipedia","source_type":"Secondary reference (L4)","source_url":"https://en.wikipedia.org/wiki/Mas_Ermieyati_Samsudin","source_date":"2026-08-06","evidence_type":"Biographical","tier":"T2","validation_status":"Verified","confidence_score":8,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":1,"issue_gap":"Women Chief role listed as present but may not reflect suspension impact (potential T5 with cycle-3 'stripped' note)","owner":"CJ-MLK-02","action_required":"Reconcile Women Chief retained vs stripped (T5 flag)","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-240","workstream":"MLK","claim":"Mas Ermieyati lost the Tanjung Bidara (Melaka) 2021 state seat to Ab Rauf Yusoh (UMNO) 3195 (44.11%) vs 3559 (49.14%); PKR Zainal Hassan 489 (6.75%)","source_name":"Wikipedia","source_type":"Secondary reference (L4)","source_url":"https://en.wikipedia.org/wiki/Mas_Ermieyati_Samsudin","source_date":"2021-11-20","evidence_type":"Electoral","tier":"T2","validation_status":"Verified","confidence_score":8,"authority":1,"traceability":2,"recency":1,"consistency":2,"completeness":2,"issue_gap":"Prior election data (2021) — recency lower","owner":"CJ-MLK-02","action_required":"None","last_reviewed":"2026-08-06"},
    # --- PIR-11 Wikipedia Adam Adli ---
    {"claim_id":"CVS-MLK-241","workstream":"MLK","claim":"Adam Adli is Acting Chair of PKR Melaka State Leadership Council (MPN), Central Leadership Council member, and Communications Director of PKR; Deputy Minister Higher Education since 16 Dec 2025 succeeding Mustapha Sakmud; MP Hang Tuah Jaya since Nov 2022 (majority 8638)","source_name":"Wikipedia","source_type":"Secondary reference (L4)","source_url":"https://en.wikipedia.org/wiki/Adam_Adli","source_date":"2026-08-06","evidence_type":"Biographical","tier":"T2","validation_status":"Verified","confidence_score":8,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":1,"issue_gap":"Wikipedia names current full Minister as Zambry Abdul Kadir — verify against cycle-3 cabinet-reshuffle scrape (potential discrepancy)","owner":"CJ-MLK-02","action_required":"Verify Higher Education Minister name (Zambry vs prior data)","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-242","workstream":"MLK","claim":"Adam Adli was 5th PKR Youth Chief (Jul 2022-May 2025), succeeded by Muhammad Kamil Abdul Munim; Deputy Youth Chief of Pakatan Harapan since Jul 2022; joined PKR 16 Sep 2021; acquitted of sedition charges Feb 2018","source_name":"Wikipedia","source_type":"Secondary reference (L4)","source_url":"https://en.wikipedia.org/wiki/Adam_Adli","source_date":"2026-08-06","evidence_type":"Biographical","tier":"T2","validation_status":"Verified","confidence_score":8,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":1,"issue_gap":"Youth Chief succession confirms upward trajectory","owner":"CJ-MLK-02","action_required":"None","last_reviewed":"2026-08-06"},
    # --- PIR-03 Wikipedia Adly + MINDEF L1 ---
    {"claim_id":"CVS-MLK-243","workstream":"MLK","claim":"KSU Datuk Lokman Hakim Ali (named witness in PAC LCS report DR.22/2026) attended Defence Professionals Programme (DPP) with Singapore and received HQIADS delegation on 4 Aug 2026 in Kota Kinabalu — reinforces PAC-MINDEF cross-POI institutional link","source_name":"MINDEF Official (mod.gov.my)","source_type":"Official (L1)","source_url":"https://www.mod.gov.my/","source_date":"2026-08-04","evidence_type":"Event/Diplomacy","tier":"T1","validation_status":"Verified","confidence_score":9,"authority":2,"traceability":2,"recency":2,"consistency":2,"completeness":1,"issue_gap":"Adly not personally featured in these items","owner":"CJ-MLK-02","action_required":"None","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-244","workstream":"MLK","claim":"Defence Minister Khaled Nordin met Singapore Permanent Secretary (Defence) Joseph Leong, ASEAN Secretary-General Kao Kim Hourn, and US Ambassador to ASEAN Kevin Kim in bilateral meetings on 3 Aug 2026 in Kuala Lumpur","source_name":"MINDEF Official (mod.gov.my)","source_type":"Official (L1)","source_url":"https://www.mod.gov.my/","source_date":"2026-08-03","evidence_type":"Event/Diplomacy","tier":"T1","validation_status":"Verified","confidence_score":9,"authority":2,"traceability":2,"recency":2,"consistency":2,"completeness":1,"issue_gap":"Adly not personally featured","owner":"CJ-MLK-02","action_required":"None","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-245","workstream":"MLK","claim":"Adly Zahari is State Chairman of PH for both Malacca (since Aug 2017) and Kelantan (since Nov 2024), Treasurer of Pakatan Harapan (coalition-level), Vice President of AMANAH, MP Alor Gajah (majority 890), and MLA Bukit Katil — sole AMANAH MLA in Malacca","source_name":"Wikipedia","source_type":"Secondary reference (L4)","source_url":"https://en.wikipedia.org/wiki/Adly_Zahari","source_date":"2026-08-06","evidence_type":"Biographical","tier":"T2","validation_status":"Verified","confidence_score":8,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":1,"issue_gap":"Dual state-chairmanship (Melaka+Kelantan) is a notable leadership expansion signal","owner":"CJ-MLK-02","action_required":"None","last_reviewed":"2026-08-06"},
    # --- PIR-04 context: 11 Aug sitting + SPRM probe ---
    {"claim_id":"CVS-MLK-246","workstream":"MLK","claim":"35-40 MPs interested in the special Dewan Rakyat sitting on 11 Aug 2026 to debate the RCI Tabung Haji report — the sitting is for Tabung Haji RCI, NOT PAC business (closes cycle-3 suggestion-3 sub-item)","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/berita-malaysia","source_date":"2026-08-06","evidence_type":"Event/Political","tier":"T2","validation_status":"Partially Verified","confidence_score":7,"authority":1,"traceability":2,"recency":2,"consistency":2,"completeness":0,"issue_gap":"Exact sitting agenda confirmation pending","owner":"CJ-MLK-02","action_required":"None; honest negative finding re PAC business","last_reviewed":"2026-08-06"},
    {"claim_id":"CVS-MLK-247","workstream":"MLK","claim":"SPRM (MACC) recorded statement from former GLC CFO for 6+ hours re abuse of power in RM370 million plantation share purchase — potential future PAC scrutiny target flagged for monitoring","source_name":"Astro Awani","source_type":"Media (L4)","source_url":"https://www.astroawani.com/berita-malaysia","source_date":"2026-08-06","evidence_type":"Event/Investigation","tier":"T2","validation_status":"Partially Verified","confidence_score":6,"authority":1,"traceability":2,"recency":2,"consistency":1,"completeness":0,"issue_gap":"GLC identity not specified; not yet a PAC matter","owner":"CJ-MLK-02","action_required":"Monitor for PAC opening of GLC proceeding","last_reviewed":"2026-08-06"},
]

# Validate field count
for c in claims:
    assert set(c.keys()) == set(FIELDS), f"Field mismatch in {c['claim_id']}: {set(c.keys()) ^ set(FIELDS)}"

# Append (preserve existing content)
with open(REGISTER, "a", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS, quoting=csv.QUOTE_MINIMAL)
    for c in claims:
        writer.writerow(c)

# Verify
with open(REGISTER, "r", encoding="utf-8") as f:
    total = sum(1 for _ in f) - 1  # minus header
print(f"Appended {len(claims)} claims (CVS-MLK-225 to CVS-MLK-247).")
print(f"Register now has {total} claims total.")
