#!/usr/bin/env python3
"""Append CJ-MLK-01 cycle 2 claims to the CVS evidence register."""
import csv, os

REG = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"
TODAY = "2026-08-05"
WS = "MLK"
OWNER = "CJMLK01"

# 20 fields: claim_id,workstream,claim,source_name,source_type,source_url,source_date,evidence_type,tier,validation_status,confidence_score,authority,traceability,recency,consistency,completeness,issue_gap,owner,action_required,last_reviewed

rows = [
    ["CVS-MLK-089",WS,"DAP Melaka withdrew from the BN-led state government on 14 July 2026 after DUN passed a constitutional amendment allowing up to 7 appointed ADUN (vote 23-5)","Scoop/Uusan/Bharian","News (L4)","https://www.scoop.my/berita/293942/dap-melaka-umum-keluar-kerajaan-negeri-tarik-sokongan-terhadap-rauf/","2026-07-14","Governance Event","T2","Partially Verified",8,1,2,2,2,1,"Vote tally needs Hansard confirmation",OWNER,"Corroborate with DUN Hansard",TODAY],
    ["CVS-MLK-090",WS,"Ab Rauf Yusoh assured Melaka administration stability after DAP exit on 15 July 2026, adopting conciliatory (non-confrontational) posture toward DAP","Melaka Hari Ini","News (L4)","https://www.melakahariini.my/ab-rauf-jamin-pentadbiran-melaka-kekal-stabil/","2026-07-15","CM Statement","T2","Partially Verified",8,1,2,2,2,1,"Direct CM statement",OWNER,"None",TODAY],
    ["CVS-MLK-091",WS,"Ab Rauf Yusoh tabled Melaka 2026 state budget of RM528.8M on 5 Dec 2025 under MeSRa framework with 204 initiatives and 3 core goals (surplus budget)","Melaka Hari Ini","News (L4)","https://www.melakahariini.my/melaka-bentang-bajet-2026-berjumlah-rm528-8-juta-kekalkan-inisiatif-bajet-lebihan/","2025-12-05","Budget/Governance","T2","Partially Verified",8,1,2,2,2,1,"Verify against DUN Hansard/Treasury gazette",OWNER,"Verify against official gazette",TODAY],
    ["CVS-MLK-092",WS,"Ab Rauf Yusoh defended the ADUN lantikan amendment (14 July 2026) as a BN manifesto commitment (Teras 1: Kestabilan Politik); appointed ADUN cannot be CM or Exco","RTM Berita","State broadcaster (L1)","https://berita.rtm.gov.my/nasional/senarai-berita-nasional/senarai-artikel/adun-lantikan-perkukuh-pentadbiran-kerajaan-melaka-ab-rauf/","2026-07-14","Governance/Manifesto","T2","Verified",9,2,2,2,2,1,"Corroborated Malaysiakini 23-5 vote",OWNER,"None",TODAY],
    ["CVS-MLK-093",WS,"Ab Rauf Yusoh stated on 2 Aug 2026 that Melaka BN is open to a 'BN Plus' cooperation formula with any party for the state election, citing the NS BN-PN precedent","Malay Mail","News (L4)","https://www.malaymail.com/news/malaysia/2026/08/02/open-to-negotiations-melaka-mb-says-willing-to-discuss-cooperation-with-any-party-for-the-coming-state-polls/229987","2026-08-02","Coalition Strategy","T2","Partially Verified",8,1,2,2,2,1,"Consistent with Zahid BN-PN NS statement",OWNER,"None",TODAY],
    ["CVS-MLK-094",WS,"Zahid Hamidi, Ab Rauf Yusoh, Asyraf Wajdi, and Akmal Saleh appeared together at the UMNO branch conference in Melaka (MITC) on 17 April 2026 focused on PRU/PRN preparation","BERNAMA","National news agency (L1)","https://www.bernama.com/bm/news.php?id=2546050","2026-04-17","Political Event","T2","Verified",9,2,2,2,2,1,"Corroborated Sinar Harian, UMNO Online",OWNER,"None",TODAY],
    ["CVS-MLK-095",WS,"Ab Rauf Yusoh publicly aligned with DPM Mohamad Hasan (Tok Mat) on 1 July 2026 in challenging DAP's Nga Kor Ming to resign over the Najib-release 'red line'","Harian Metro","News (L4)","https://www.hmetro.com.my/mutakhir/2026/07/1377553/kalau-nak-letak-jawatan-letaklah-ab-rauf","2026-07-01","Political Alignment","T2","Partially Verified",8,1,2,2,2,1,"First direct Ab Rauf-Tok Mat alignment evidence",OWNER,"None",TODAY],
    ["CVS-MLK-096",WS,"Ab Rauf Yusoh claimed credit for bringing over 86% new candidate faces in the 2021 PRN Melaka and will field a balanced old/new mix for the next PRN","BN Comms/BERNAMA","Official party platform (L2)","https://bncomms.my/2026/04/30/bn-beri-bayangan-calon-prn-melaka-seimbang-antara-muka-lama-baharu/","2026-04-30","Candidate Selection","T2","Partially Verified",8,2,2,2,1,1,"Verify 86% figure against 2021 SPR candidate list",OWNER,"Verify against SPR",TODAY],
    ["CVS-MLK-097",WS,"Ab Rauf Yusoh formally rejected Akmal Saleh's resignation as Melaka Exco on 8 April 2026, exercising his constitutional CM authority to retain Akmal in office","Astro Awani","News (L4)","https://www.astroawani.com/berita-politik/rauf-tolak-peletakan-jawatan-akmal-saleh-kekal-sebagai-exco-melaka","2026-04-08","Executive Decision","T2","Partially Verified",8,1,2,2,2,1,"Corroborated Bharian, Melaka Hari Ini",OWNER,"None",TODAY],
    ["CVS-MLK-098",WS,"Akmal Saleh submitted his political positions to both Zahid Hamidi (candidate selection power) and Ab Rauf Yusoh (Exco appointment power), revealing Ab Rauf as his political mentor since student days","FMT/BERNAMA","National news agency (L1)","https://www.freemalaysiatoday.com/category/bahasa/tempatan/2026/01/12/kedudukan-politik-akmal-komited-akur-keputusan-pimpinan","2026-01-12","Authority/Relationship","T2","Partially Verified",8,2,2,2,1,1,"Authority triangle mapped",OWNER,"None",TODAY],
    ["CVS-MLK-099",WS,"DAP was accused of double standards in July 2026 for campaigning against Akmal in Johor while its Melaka assemblymen serve in the same state government as him (MCA VP Lim Ban Hong)","The Star","News (L4)","https://www.thestar.com.my/news/nation/2026/07/05/dap-criticised-for-anti-akmal-campaign-amid-collaboration-in-melaka","2026-07-05","Electoral Impact","T2","Partially Verified",8,1,2,2,2,1,"Measurable multiracial electoral tension",OWNER,"None",TODAY],
    ["CVS-MLK-100",WS,"Teresa Kok's defamation suit against Akmal Saleh (filed Oct 2024 over 7 Sept 2024 TikTok halal-cert video) headed to trial 12-13 Feb 2026 at Melaka High Court; RM25M demand; injunction sought","Malay Mail/BERNAMA","National news agency (L1)","https://www.malaymail.com/news/malaysia/2026/01/12/teresa-kok-vs-akmal-saleh-defamation-suit-heads-to-trial-after-failed-mediation/205169","2026-01-12","Legal","T2","Verified",9,2,2,2,2,1,"Corroborated NST/FMT/Sun; monitor trial outcome",OWNER,"Monitor Feb 2026 trial outcome",TODAY],
    ["CVS-MLK-101",WS,"Akmal Saleh hinted at resigning as UMNO Youth chief in Jan 2026 after Zahid rejected his Muafakat Nasional revival and Unity Government exit proposals; grassroots viewed him as irreplaceable","Malay Mail","News (L4)","https://www.malaymail.com/news/malaysia/2026/01/15/no-fear-no-surrender-to-stepping-aside-umno-youth-weighs-akmals-future/205432","2026-01-15","Succession Positioning","T2","Partially Verified",8,1,2,2,2,1,"Corroborated Malay Mail Jan 9, Kosmo Feb 5",OWNER,"None",TODAY],
    ["CVS-MLK-102",WS,"Pusat Komas (NGO) assessed in Jan 2026 that Akmal's 'fight DAP to the end' rhetoric rallies anti-Chinese/minority sentiment, citing 2023-2024 Racism Reports [ASSESSMENT - T3]","Scoop/Pusat Komas","NGO analysis (L4)","https://www.scoop.my/opinion-analysis/279690/rallying-fear-not-policies-akmals-divisive-call-undermines-unity-pusat-komas/","2026-01-16","Analytical Assessment","T3","Inferred",7,1,2,2,1,1,"Analytical interpretation not fact; needs human review to elevate",OWNER,"Human review to elevate T3",TODAY],
    ["CVS-MLK-103",WS,"Ab Rauf Yusoh declared Melaka as the arena of UMNO's revival on 2 May 2026, citing BN's 21/28 seat win (UMNO 18) and ~150 days to PRN, endorsing Zahid's Rumah Bangsa initiative","Utusan Malaysia","News (L4)","https://www.utusan.com.my/nasional/politik/2026/05/melaka-medan-kebangkitan-semula-umno-ab-rauf/","2026-05-02","Political Declaration","T2","Partially Verified",8,1,2,2,2,1,"Verify 21/28 seat count vs 2021 PRN results",OWNER,"Verify against SPR",TODAY],
    ["CVS-MLK-104",WS,"Ab Rauf Yusoh hinted on 17 May 2026 that the Melaka state election could be held within four months (~September 2026), avoiding Ramadan/Hari Raya","The Star","News (L4)","https://www.thestar.com.my/news/nation/2026/05/17/melaka-cm-hints-at-state-polls-within-four-months","2026-05-17","Election Timeline","T2","Verified",8,1,2,2,2,1,"Corroborated Utusan 150 days, BN Comms, Wikipedia Nov 2026 deadline",OWNER,"None",TODAY],
    ["CVS-MLK-105",WS,"Akmal Saleh dared DAP Youth on 28 May 2026 to quit BN-led state governments in Perak and Pahang, weaponising his own twice-rejected Melaka Exco resignation as national anti-DAP leverage","FMT","News (L4)","https://www.freemalaysiatoday.com/category/nation/2026/05/28/bring-it-on-akmal-dares-dap-youth-to-quit-bn-led-state-govts","2026-05-28","Rhetoric/Electoral","T2","Partially Verified",8,1,2,2,2,1,"Akmal's own Facebook post",OWNER,"None",TODAY],
    ["CVS-MLK-106",WS,"Ab Rauf Yusoh ('Tok Rauf') led the BN Melaka machinery to campaign in Muar, Johor for BN candidate Ashari Md Sharif (N15 DUN Maharani) on 2 July 2026","Melaka Report","Local news (L4)","https://www.melakareport.com/portal/2026/07/03/tok-rauf-pimpin-jentera-barisan-nasional-melaka-perkukuh-gerak-kerja-kempen-di-muar/","2026-07-02","Mobilization","T2","Partially Verified",7,1,2,2,1,1,"Small local outlet; needs mainstream corroboration",OWNER,"Corroborate with mainstream outlet",TODAY],
    ["CVS-MLK-107",WS,"Akmal Saleh rebuked Amanah VP Adly Zahari on 22 June 2026 during Johor PRN campaign for allegedly slandering Melaka people, defending his Merlimau/Sungai Rambai constituency","UMNO Online","Official party portal (L2)","https://umno-online.my/2026/06/22/dr-akmal-bidas-adly-berkempen-janganlah-sampai-memfitnah-memburukkan-rakyat-negeri-melaka/","2026-06-22","Rhetoric/Constituency","T2","Partially Verified",8,2,2,2,1,1,"Akmal's Facebook + official UMNO portal",OWNER,"None",TODAY],
    ["CVS-MLK-108",WS,"Ab Rauf Yusoh welcomed the federal Belanjawan MADANI 2026 (RM470B) in Oct 2025 with Melaka 'wishlist' projects approved (roads, schools, Museum Samudera, tourism); Melaka = VMY2026 launch host","Berita Harian","News (L4)","https://www.bharian.com.my/berita/nasional/2025/10/1457018/belanjawan-2026-kelulusan-projek-dalam-wishlist-melaka","2025-10-10","State-Federal Alignment","T2","Partially Verified",8,1,2,2,2,1,"State-federal alignment evidence",OWNER,"None",TODAY],
]

with open(REG, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    for r in rows:
        w.writerow(r)

print(f"Appended {len(rows)} claims (CVS-MLK-089 to CVS-MLK-108) to evidence register")
print(f"Register now has {sum(1 for _ in open(REG, encoding='utf-8'))} lines")
