#!/usr/bin/env python3
"""Append CJ-MLK-02 cycle 7 CVS claims to the evidence register.
Uses csv.writer for correct quoting/escaping. Idempotency: skips if last claim already >= CVS-MLK-379."""
import csv, os, sys

REGISTER = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"

# Detect existing max claim id to avoid duplicate appends
existing_ids = set()
max_num = 0
if os.path.exists(REGISTER):
    with open(REGISTER, newline='', encoding='utf-8') as f:
        for row in csv.reader(f):
            if row and row[0].startswith("CVS-MLK-"):
                existing_ids.add(row[0])
                try:
                    n = int(row[0].split('-')[-1])
                    if n > max_num:
                        max_num = n
                except ValueError:
                    pass

if any(f"CVS-MLK-{n}" in existing_ids for n in range(379, 406)):
    print(f"SKIP: some cycle-7 claims already present (max existing={max_num}). No append.")
    sys.exit(0)

# 20-field schema
# claim_id,workstream,claim,source_name,source_type,source_url,source_date,
# evidence_type,tier,validation_status,confidence_score,authority,traceability,
# recency,consistency,completeness,issue_gap,owner,action_required,last_reviewed
rows = [
["CVS-MLK-379","CJ-MLK-02","Defence Minister Mohamed Khaled Nordin announced Malaysia-Cambodia defence cooperation strengthening — building collective resilience; both nations committed to enhancing bilateral defence ties; focus on defence and security; contributes to ASEAN collective resilience (7 Aug 2026).","Astro Awani","L4","https://www.astroawani.com/search?q=pertahanan","2026-08-07","News report","T2","Verified","7","1","2","2","2","1","PIR-03 MINDEF bilateral diplomacy; Adly superior (Khaled Nordin)","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-380","CJ-MLK-02","Multiple defence cooperation agreements signed during Khaled Nordin official visit to Vietnam; met Vietnam PM Le Minh Hung; Malaysia has close defence relations with Vietnam; Vietnam considered trusted partner; both share same strategic views; uphold ASEAN principles (dialogue and diplomacy); strategic defence cooperation strengthened (6 Aug 2026).","Astro Awani","L4","https://www.astroawani.com/search?q=pertahanan","2026-08-06","News report","T2","Verified","7","1","2","2","2","1","PIR-03 MINDEF bilateral diplomacy; Vietnam visit precedes Cambodia visit","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-381","CJ-MLK-02","PM Anwar Ibrahim announced ATM (Armed Forces) and PDRM (Police) promotion processes to be simplified and accelerated; aimed at boosting morale of police and military personnel (7 Aug 2026).","Astro Awani","L4","https://www.astroawani.com/search?q=pertahanan","2026-08-07","News report","T2","Verified","7","1","2","2","2","1","PIR-03 relevant (ATM = military under MINDEF); PM-level policy announcement","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-382","CJ-MLK-02","Khaled Nordin conducted a working visit (lawatan kerja) to Vietnam and Cambodia on 7 Aug 2026; Astro Awani video coverage (01:50 duration).","Astro Awani","L4","https://www.astroawani.com/search?q=pertahanan","2026-08-07","News report (video)","T2","Verified","7","1","2","2","2","1","Combined Vietnam-Cambodia defence diplomacy tour; MINDEF activity","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-383","CJ-MLK-02","Indonesia begins first domestic construction of Scorpene submarines; marks significant milestone in defence self-reliance and manufacturing capability (7 Aug 2026).","Astro Awani","L4","https://www.astroawani.com/search?q=pertahanan","2026-08-07","News report","T2","Verified","6","1","2","2","1","1","Regional defence-industry context; comparator for Malaysia Dasar Industri Pertahanan Negara","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-384","CJ-MLK-02","PAC latest media statement is dated 9 July 2026 (Penyata Pengurusan Kenderaan Kerajaan di bawah Perjanjian Konsesi / Government Vehicle Management under Concession Agreement); no August 2026 statements issued — confirming August quiet period under Mas Ermieyati.","Parlimen.gov.my PAC kenyataan media page","L2","https://www.parlimen.gov.my/pac/kenyataan_media_2025.html","2026-07-09","Official parliamentary record","T2","Verified","8","2","2","2","2","1","L2 source; latest PAC activity = 9 Jul; September = next expected window","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-385","CJ-MLK-02","All PAC media statements from Feb 2025 to Jul 2026 are issued by YB Datuk Wira Mas Ermieyati Binti Samsudin as Pengerusi PAC — confirming continuous active chairmanship through July 2026.","Parlimen.gov.my PAC kenyataan media page","L2","https://www.parlimen.gov.my/pac/kenyataan_media_2025.html","2026-07-09","Official parliamentary record","T2","Verified","8","2","2","2","2","1","L2 source; confirms Mas Ermieyati active PAC chair despite BERSATU suspension","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-386","CJ-MLK-02","PAC 2026 activity timeline (L2 confirmed): 8 Jan IWK visit; 21 Jan general statement; 30 Jan LCS visit; 2 Mar LKAN briefing (origin of UKM/R&D&C&I/PHB proceedings); 3 Mar FELCRA statement; 11 Jun KLIA working visit; 24 Jun general statement; 1 Jul MAHB statement; 9 Jul gov vehicle management statement.","Parlimen.gov.my PAC kenyataan media page","L2","https://www.parlimen.gov.my/pac/kenyataan_media_2025.html","2026-07-09","Official parliamentary record","T2","Verified","8","2","2","2","2","1","Comprehensive L2 PAC activity timeline; corroborates cycle-6 findings","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-387","CJ-MLK-02","New PAC member YB Bayan Baru appointed on 16 December 2025; PAC media statement issued for the appointment.","Parlimen.gov.my PAC kenyataan media page","L2","https://www.parlimen.gov.my/pac/kenyataan_media_2025.html","2025-12-16","Official parliamentary record","T2","Verified","7","2","2","1","2","1","PAC membership change; Dec 2025","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-388","CJ-MLK-02","PKR Central Leadership Council (MPP) agreed to grant Nurul Izzah Anwar temporary leave from Deputy President role after the 2026 National Congress in Melaka; VP Saifuddin Nasution Ismail acting during leave; Wikipedia confirms on leave since 16 Aug 2026.","Astro Awani + Wikipedia","L4/L1","https://www.astroawani.com/berita-politik","2026-08-07","News report + Wikipedia","T2","Verified","8","2","2","2","2","1","Major PKR leadership change timed with Melaka congress; PIR-11 context","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-389","CJ-MLK-02","Nurul Izzah Anwar stepped down (lepas jawatan) from PKR Deputy President role to focus on further studies; expressed gratitude to PKR President Anwar Ibrahim and party leadership for accepting her decision.","Astro Awani","L4","https://www.astroawani.com/berita-politik","2026-08-07","News report","T2","Verified","7","1","2","2","2","1","Leave then resignation sequence; timing with Melaka congress","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-390","CJ-MLK-02","PKR holds 29 of 222 Dewan Rakyat seats; 7 Rafizi Faction MP status unclear following internal party split; Secretary-General Fuziah Salleh; membership 1153212 (2024).","Wikipedia (PKR)","L1","https://en.wikipedia.org/wiki/People%27s_Justice_Party_(Malaysia)","2026-08-08","Reference","T2","Verified","7","2","2","1","2","1","Party factional context; Rafizi faction MPs status unclear","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-391","CJ-MLK-02","PAS President Abdul Hadi Awang claimed Bersatu automatically exited PN following intent to form new coalition; Azmin Ali insists Bersatu remains legitimate PN member; coalition status disputed (7 Aug 2026).","Astro Awani","L4","https://www.astroawani.com/berita-politik","2026-08-07","News report","T2","Verified","7","1","2","2","1","1","PN coalition status T5-adjacent; Mas Ermieyati BERSATU context (she is suspended)","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-392","CJ-MLK-02","Analysts predict PH will strengthen position before PRU16 (possibly late 2027) after weathering three state elections; BN-PN alignment faces more uncertain (berliku) path.","Astro Awani","L4","https://www.astroawani.com/berita-politik","2026-08-07","News report (analyst assessment)","T2","Verified","6","1","2","2","1","1","Analyst opinion; PRU16 outlook context for PIR-11","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-393","CJ-MLK-02","Ilham Centre chief Hisommudin Bakar analysis: BN-PN Blue Wave coalition could potentially sweep 122 seats in PRU16 from Peninsular Malaysia alone.","Free Malaysia Today","L4","https://www.freemalaysiatoday.com/","2026-08-07","News report (analyst)","T2","Partially Verified","6","1","1","2","1","1","Analyst projection; single-source; counter-narrative to CVS-MLK-392","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-394","CJ-MLK-02","AMK (Angkatan Muda Keadilan / PKR Youth Wing) ramps up preparations for Melaka polls; led by Kamil Munim (current AMK leader); 07 Aug 2026.","The Edge Malaysia","L4","https://www.theedgemalaysia.com/","2026-08-07","News report","T2","Verified","7","1","2","2","2","1","PIR-11 relevant; Adam Adli was 5th Youth Chief PKR (2022-2025); Kamil Munim is successor","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-395","CJ-MLK-02","PM Anwar Ibrahim ordered full report on RM330 million gap in proposed Felda hotel sale; spoke during Semarak Kenegaraan programme at Terendak Camp Melaka (a major military installation) on 7 Aug 2026 — PIR-03 Melaka nexus signal (PM at Melaka military camp).","The Edge Malaysia + Malay Mail","L4","https://www.theedgemalaysia.com/","2026-08-07","News report","T2","Verified","7","1","2","2","2","1","PIR-03 Melaka nexus — PM at Terendak Camp (Kem Terendak military base in Melaka)","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-396","CJ-MLK-02","Cabinet directed Ministry of Home Affairs (KDN) and Ministry of Transport (MOT) to submit comprehensive airport security strengthening plan within two weeks (07 Aug 2026 Bernama).","The Edge Malaysia / Bernama","L4","https://www.theedgemalaysia.com/","2026-08-07","News report (Bernama)","T2","Verified","7","1","2","2","2","1","Security policy; cabinet-level directive; airport security post-KKIA incident","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-397","CJ-MLK-02","Rafizi Ramli announced Melaka election candidate preparations entered final stage; candidates to be announced Aug 15; state election not yet called (FMT 7-8 Aug 2026). Note: extraction ambiguity — Bersama may mean together (Malay) not a party name.","Free Malaysia Today","L4","https://www.freemalaysiatoday.com/","2026-08-07","News report","T2","Partially Verified","6","1","1","2","1","1","Extraction ambiguity (Bersama = together or party?); Aug 15 = PKR congress day","CJ-MLK-02","Corroboration needed on Bersama meaning","2026-08-08"],
["CVS-MLK-398","CJ-MLK-02","MACC concluded recording statement of ex-CFO of statutory body; probe involves abuse of power in purchase of shares in two plantation companies valued at ~RM370 million; related to Tabung Haji RCI findings (07 Aug 2026).","The Edge Malaysia","L4","https://www.theedgemalaysia.com/","2026-08-07","News report","T2","Verified","7","1","2","2","2","1","MACC enforcement; Tabung Haji RCI follow-up; PIR-04 adjacent (govt accountability)","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-399","CJ-MLK-02","Adly bin Zahari is Deputy Minister of Defence since 10 Dec 2022 under Minister Mohamed Khaled Nordin (since 2023); also Vice-President of AMANAH (since Sep 2021); PH State Chairman for Malacca (since Aug 2017) and Kelantan (since Nov 2024); MP for Alor Gajah P135; MLA for Bukit Katil Melaka.","Wikipedia + malaysiacabinet.com","L1","https://en.wikipedia.org/wiki/Adly_Zahari","2026-08-08","Reference","T2","Verified","7","2","2","1","2","1","L1 Wikipedia; corroborates cycle-6 CVS-MLK-340; additional VP AMANAH + dual PH state chair detail","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-400","CJ-MLK-02","Mas Ermieyati Samsudin is Chairperson of PAC since 4 Apr 2023 (second female PAC Chair); MP for Masjid Tanah P134 since 2013; Women Chief of BERSATU since Oct 2024; BERSATU membership suspended since 2026 (not resigned — suspended); UKM law graduate; born in Melaka.","Wikipedia","L1","https://en.wikipedia.org/wiki/Mas_Ermieyati_Samsudin","2026-08-08","Reference","T2","Verified","7","2","2","1","2","1","L1 Wikipedia; suspended (not resigned) distinction important; corroborates Mar 2026 BERSATU suspension","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-401","CJ-MLK-02","Adam Adli bin Abd Halim is Deputy Minister of Higher Education since 16 Dec 2025; MP for Hang Tuah Jaya P137 since Nov 2022; Acting Chair of PKR Melaka State Leadership Council (MPN); Communications Director PKR; Central Leadership Council member PKR; Deputy Youth Chief of PH.","Wikipedia","L1","https://en.wikipedia.org/wiki/Adam_Adli","2026-08-08","Reference","T2","Verified","7","2","2","1","2","1","L1 Wikipedia; corroborates cycle-6 CVS-MLK-341; adds Acting PKR Melaka MPN Chair + Comms Director + CLC member","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-402","CJ-MLK-02","Adam Adli won Hang Tuah Jaya P137 in GE15 with 39418 votes (41.72%); majority 8638; defeated UMNO (30780/32.58%) and BERSATU (23549/24.92%); turnout 79.74%.","Wikipedia","L1","https://en.wikipedia.org/wiki/Adam_Adli","2022-11-19","Reference","T2","Verified","7","2","2","1","2","1","L1 Wikipedia; GE15 election results; baseline electoral data","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-403","CJ-MLK-02","Mas Ermieyati BERSATU membership is suspended since 2026 (Wikipedia table: suspended not resigned); she remains Women Chief of BERSATU per Wikipedia (since Oct 2024) despite Feb 2026 resignation as Masjid Tanah division chief + Srikandi chief; reconciles cycle-6 ambiguity.","Wikipedia","L1","https://en.wikipedia.org/wiki/Mas_Ermieyati_Samsudin","2026-08-08","Reference","T2","Verified","7","2","2","1","2","1","Reconciles cycle-6 CVS-MLK-342 ambiguity (member vs ex-member); suspended is the correct status","CJ-MLK-02","None","2026-08-08"],
["CVS-MLK-404","CJ-MLK-02","[ASSESSMENT] Khaled Nordin's Vietnam-Cambodia defence diplomacy tour (6-7 Aug 2026) represents MINDEF's most active bilateral engagement burst; as Adly's superior this shapes the defence policy environment Adly operates in; ASEAN defence diplomacy is the current MINDEF posture.","Astro Awani (search: pertahanan)","L4","https://www.astroawani.com/search?q=pertahanan","2026-08-07","Assessment","T3","Inferred","6","1","2","2","1","0","Analytical interpretation; not direct fact; Adly's specific role in these visits not confirmed","CJ-MLK-02","None — analytical","2026-08-08"],
["CVS-MLK-405","CJ-MLK-02","[ASSESSMENT] Nurul Izzah's PKR Deputy President leave/resignation timed with the Melaka congress (15-16 Aug) creates a leadership vacuum that elevates the congress significance for Adam Adli's political trajectory; as Acting PKR Melaka MPN Chair his congress visibility is high; the deputy president vacancy may create advancement opportunities within PKR leadership.","Astro Awani + Wikipedia","L4/L1","https://www.astroawani.com/berita-politik","2026-08-07","Assessment","T3","Inferred","6","1","2","2","1","0","Analytical interpretation; speculative on advancement implications; forward-monitoring","CJ-MLK-02","None — analytical","2026-08-08"],
]

with open(REGISTER, 'a', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    for r in rows:
        cid = r[0]
        if cid in existing_ids:
            continue
        w.writerow(r)
        print(f"APPENDED {cid}")

print(f"Done. {len(rows)} rows processed. Max existing before: {max_num}")
