#!/usr/bin/env python3
"""CVS Append Script — CJ-MLK-02 Cycle 5 (2026-08-07)
Appends 24 new claims (CVS-MLK-300 to 323) to evidence register.
"""
import csv
from pathlib import Path

REGISTER = Path("/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv")
FIELDS = "claim_id,workstream,claim,source_name,source_type,source_url,source_date,evidence_type,tier,validation_status,confidence_score,authority,traceability,recency,consistency,completeness,issue_gap,owner,action_required,last_reviewed".split(",")

# 20-field schema rows. owner=CJ-MLK-02, last_reviewed=2026-08-07
O = "CJ-MLK-02"
D = "2026-08-07"

rows = [
# Norway missile NSM timeline (PIR-03/04)
["CVS-MLK-300","CJ-MLK-02","Norway missile identified as Naval Strike Missile (NSM) by Kongsberg Defence & Aerospace AS (KDA) Norway; Malaysia CANCELLED the purchase contract; distinct from LCS (DR.22/2026) though NSM replacement must integrate with LCS Combat Management System (CMS)","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/tuntutan-ganti-rugi-kontrak-peluru-berpandu-norway-malaysia-telah-ambil-semua-langkah-perlu","2026-06-25","News report (Bernama)","T2","Verified","7","1","2","2","2","1","Specific cancellation date not stated","CJ-MLK-02","None",D],
["CVS-MLK-301","CJ-MLK-02","PAC summoned MINDEF to clarify Norway missile (peluru berpandu Norway) issue on 11 Jun 2026; PAC Chairman Datuk Mas Ermieyati Samsudin; related to PAC working visit at KLIA Terminal 1","Astro Awani","L4","https://www.astroawani.com/search?q=peluru+berpandu+Norway","2026-06-11","News report (index)","T2","Verified","7","1","2","2","2","1","Index-level; full article URL not directly extracted","CJ-MLK-02","None",D],
["CVS-MLK-302","CJ-MLK-02","PAC received special briefing from MINDEF on Norway missile issue on 24 Jun 2026 (day before Khaled Nordin's statement); PAC urged govt to strengthen mitigation and diplomacy for fair resolution and fiscal sovereignty","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/tuntutan-ganti-rugi-kontrak-peluru-berpandu-norway-malaysia-telah-ambil-semua-langkah-perlu","2026-06-25","News report (Bernama)","T2","Verified","7","1","2","2","2","2","None","CJ-MLK-02","None",D],
["CVS-MLK-303","CJ-MLK-02","Defence Minister Khaled Nordin: Malaysia has taken all necessary steps on NSM compensation claims; MINDEF and Foreign Ministry sent notice to Norway govt requesting Norway to facilitate/mediate between MINDEF and KDA","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/tuntutan-ganti-rugi-kontrak-peluru-berpandu-norway-malaysia-telah-ambil-semua-langkah-perlu","2026-06-25","News report (Bernama)","T2","Verified","7","1","2","2","2","2","None","CJ-MLK-02","None",D],
["CVS-MLK-304","CJ-MLK-02","TLDM technical evaluation for NSM replacement expected to complete end July 2026; evaluating multiple SSM systems from OEMs across countries; criteria: LCS CMS integration, delivery timeline, total cost, capability vs NSM","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/tldm-selesai-penilaian-teknikal-ganti-peluru-berpandu-norway-akhir-julai-menteri","2026-07-06","News report (Dewan Rakyat statement)","T2","Verified","7","1","2","2","2","2","None","CJ-MLK-02","None",D],
["CVS-MLK-305","CJ-MLK-02","Khaled Nordin strategic warning: over-reliance on foreign supply chain brings major strategic risk; long-term solution requires local defence industry development and reduced dependence on foreign technology/expertise","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/tldm-selesai-penilaian-teknikal-ganti-peluru-berpandu-norway-akhir-julai-menteri","2026-07-06","Ministerial statement (Dewan Rakyat)","T2","Verified","7","1","2","2","2","1","No Melaka-specific element in this policy","CJ-MLK-02","None",D],
["CVS-MLK-306","CJ-MLK-02","MINDEF formed special committee to evaluate legal action and compensation following Norway missile contract cancellation (14 May 2026); context includes LCS 1 Maharaja Lela at TLDM Lumut base","Astro Awani","L4","https://www.astroawani.com/search?q=peluru+berpandu+Norway","2026-05-14","News report (index)","T2","Verified","7","1","2","2","2","1","Index-level only","CJ-MLK-02","None",D],
["CVS-MLK-307","CJ-MLK-02","Malaysia continues diplomatic efforts regarding Norway missile acquisition; announced by Communications Minister Fahmi Fadzil at weekly Cabinet press conference (13 May 2026)","Astro Awani","L4","https://www.astroawani.com/search?q=peluru+berpandu+Norway","2026-05-13","News report (index)","T2","Verified","6","1","2","2","2","1","Index-level only; brief mention","CJ-MLK-02","None",D],
["CVS-MLK-308","CJ-MLK-02","Armed Forces Chief Tan Sri Malek Razak Sulaiman present at launch of Defence Strategic Plan 2026-2030 and Defence Capacity Action Framework (25 Jun 2026); same launch where Khaled Nordin addressed NSM compensation","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/tuntutan-ganti-rugi-kontrak-peluru-berpandu-norway-malaysia-telah-ambil-semua-langkah-perlu","2026-06-25","News report (Bernama)","T2","Verified","7","1","2","2","2","2","None","CJ-MLK-02","None",D],
# PH-BN Melaka divorce (PIR-03/11)
["CVS-MLK-309","CJ-MLK-02","PH-BN Melaka officially divorced 16 Jul 2026; joint statement signed by Adly Zahari (PH Melaka Chair) + Adam Adli Abdul Halim (Acting PKR Melaka Chair) + Khoo Poay Tiong (DAP Melaka) + Datuk Ashraf Mukhlis Minghat (AMANAH Melaka)","Astro Awani","L4","https://www.astroawani.com/berita-politik/tidak-lagi-bersama-ph-bn-melaka-sah-bercerai","2026-07-16","News report","T2","Verified","8","1","2","2","2","2","Cross-POI: both Adly and Adam Adli named","CJ-MLK-02","None",D],
["CVS-MLK-310","CJ-MLK-02","4 DAP ADUN + 1 Amanah ADUN withdrew from Melaka state govt; released all Exco/Deputy Exco/Deputy Speaker positions; all PH PBT council + JPKK positions released; effective 31 Jul 2026","Astro Awani","L4","https://www.astroawani.com/berita-politik/tidak-lagi-bersama-ph-bn-melaka-sah-bercerai","2026-07-16","News report","T2","Verified","8","1","2","2","2","2","None","CJ-MLK-02","None",D],
["CVS-MLK-311","CJ-MLK-02","Adam Adli (Acting PKR Melaka Chair + Deputy Min Higher Ed) cautioned against rushed decisions affecting Melaka state stability (15 Jul 2026); urged consensus and negotiation; noted DAP withdrawal was NOT collectively agreed at PH Melaka leadership level","Astro Awani","L4","https://www.astroawani.com/berita-politik/jangan-tergesa-gesa-buat-keputusan-jejas-kestabilan-negeri-keadilan-melaka","2026-07-15","News report (Bernama)","T2","Verified","8","1","2","2","2","2","None","CJ-MLK-02","None",D],
["CVS-MLK-312","CJ-MLK-02","Adly Zahari (15 Jul 2026) stated he still supports CM Ab Rauf Yusoh; defended PH rejection of constitutional amendment Bill; warned 7 appointed ADUN could erode democracy; position questioned when 4 DAP ADUN sat in opposition","Astro Awani","L4","https://www.astroawani.com/search?q=Adly+Zahari","2026-07-15","News report (index + video)","T2","Verified","7","1","2","2","2","1","Index-level; video caption only","CJ-MLK-02","None",D],
["CVS-MLK-313","CJ-MLK-02","Melaka DUN passed Enakmen Perlembagaan Negeri (Melaka) (Pindaan) 2026 allowing appointment of up to 7 ADUN Lantikan (appointed assemblymen) rather than election; PH opposed as anti-democratic; passed 14 Jul 2026","Astro Awani","L4","https://www.astroawani.com/berita-politik/tidak-lagi-bersama-ph-bn-melaka-sah-bercerai","2026-07-16","News report","T2","Verified","8","1","2","2","2","2","None","CJ-MLK-02","None",D],
# AUKU follow-through (PIR-11)
["CVS-MLK-314","CJ-MLK-02","Adam Adli (Deputy Min Higher Ed) agreed to dialogue with Liga Mahasiswa Malaysia re AUKU (19 Jan 2026); Liga Mahasiswa had challenged him to open dialogue same day; documented AUKU engagement","Astro Awani","L4","https://www.astroawani.com/search?q=AUKU","2026-01-19","News report (index)","T2","Verified","7","1","2","2","2","1","Article URL 404; index headline only","CJ-MLK-02","None",D],
["CVS-MLK-315","CJ-MLK-02","Gerakan Mahasiswa planned march to Parliament demanding AUKU abolition (mansuh AUKU) on 6 Feb 2026; UM cautioned free speech must be exercised with wisdom and safety (7 Feb 2026)","Astro Awani","L4","https://www.astroawani.com/search?q=AUKU","2026-02-06","News report (index + video)","T2","Verified","6","1","2","2","2","1","Index-level; video captions","CJ-MLK-02","None",D],
["CVS-MLK-316","CJ-MLK-02","Government position on AUKU = incremental reform/improvement NOT abolition; Minister Zambry Abdul Kadir stated 'AUKU akan terus diperbaiki demi mahasiswa' (Apr 2024); defended VC appointment processes (Feb 2025)","Astro Awani","L4","https://www.astroawani.com/search?q=AUKU","2024-04-03","News report (index)","T2","Verified","7","1","2","1","2","2","Older source (2024) but policy stance sustained","CJ-MLK-02","None",D],
["CVS-MLK-317","CJ-MLK-02","Higher Education Minister confirmed as Datuk Seri Dr. Zambry Abdul Kadir based on multiple AUKU policy statements attributed to him as minister (Apr 2024, Feb 2025); resolves cycle-4 T5 flag CVS-MLK-247","Astro Awani","L4","https://www.astroawani.com/search?q=AUKU","2026-08-07","Cross-reference (index + cycle-4)","T2","Verified","8","1","2","2","2","2","Resolves T5 from cycle 4","CJ-MLK-02","None",D],
# MINDEF August (L1)
["CVS-MLK-318","CJ-MLK-02","KSU Datuk Lokman Hakim Ali (PAC LCS witness DR.22/2026) co-chaired 63rd Five Power Defence Arrangements (FPDA) Consultative Council with Permanent Secretary Defence Singapore (5 Aug 2026, Kota Kinabalu)","MINDEF Official (mod.gov.my)","L1","https://www.mod.gov.my/","2026-08-05","Official govt website news","T1","Verified","9","2","2","2","2","2","L1 official source","CJ-MLK-02","None",D],
["CVS-MLK-319","CJ-MLK-02","KSU Lokman Hakim held bilateral meeting with British High Commissioner to Malaysia (4 Aug 2026); received HQIADS courtesy call; attended DPP with Singapore; officiated FPDA FCC dinner (Kota Kinabalu)","MINDEF Official (mod.gov.my)","L1","https://www.mod.gov.my/","2026-08-04","Official govt website news","T1","Verified","9","2","2","2","2","2","L1 official source","CJ-MLK-02","None",D],
["CVS-MLK-320","CJ-MLK-02","Defence Minister Khaled Nordin held bilateral meetings with ASEAN Sec-Gen Dr. Kao Kim Hourn and US Ambassador to ASEAN Kevin Kim (3 Aug 2026, Kuala Lumpur); Singapore Perm Sec Defence Joseph Leong courtesy call to Minister","MINDEF Official (mod.gov.my)","L1","https://www.mod.gov.my/","2026-08-03","Official govt website news","T1","Verified","9","2","2","2","2","2","L1 official source","CJ-MLK-02","None",D],
# Adly PH values + PKR congress T5 + cooking oil
["CVS-MLK-321","CJ-MLK-02","Adly Zahari (Naib Presiden Amanah) stated PH remains committed to value-based politics and governance capability at 11th Pulau Pinang Amanah Convention 2026 (2 Aug 2026, Bukit Mertajam); post-Melaka divorce PH leadership signal","Astro Awani","L4","https://www.astroawani.com/search?q=Adly+Zahari","2026-08-02","News report (index)","T2","Verified","6","1","2","2","2","1","Index headline only","CJ-MLK-02","None",D],
["CVS-MLK-322","CJ-MLK-02","PKR National Congress 2026 date DISPUTED (T5): Astro Awani Jan 2026 article says Jun 25-28 Melaka; CJ-MLK-01 cycle 4 (6 Aug) logged Aug 15-16 at MITC Ayer Keroh; no June 2026 congress coverage found supporting rescheduling hypothesis","Astro Awani / CJ-MLK-01","L4","https://www.astroawani.com/search?q=kongres+nasional+PKR","2026-08-07","Cross-workstream comparison","T5","Disputed","5","1","2","2","1","1","Date discrepancy unresolved; rescheduling not confirmed","CJ-MLK-02","Human review / reconciliation with CJ-MLK-01",D],
["CVS-MLK-323","CJ-MLK-02","PAC called several witnesses to give statements re cooking oil price control and subsidy (4 Sep 2025); article titled 'Kawalan harga, subsidi minyak masak: PAC panggil beberapa saksi beri keterangan'","Astro Awani","L4","https://www.astroawani.com/berita-malaysia/kawalan-harga-subsidi-minyak-masak-pac-panggil-beberapa-saksi-beri-keterangan-537136","2025-09-04","News report","T2","Partially Verified","6","1","2","1","2","1","Sep 2025 article; specific findings not extracted (page timeout)","CJ-MLK-02","None",D],
]

with open(REGISTER, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    for r in rows:
        w.writerow(r)

print(f"Appended {len(rows)} claims (CVS-MLK-300 to 323) to evidence register")
print(f"Expected final row count: 300 (header) + 300 to 323 = 324 data rows")

# Verify
with open(REGISTER, "r", encoding="utf-8") as f:
    total = sum(1 for _ in f) - 1
print(f"Verified total claims in register: {total}")
