#!/usr/bin/env python3
"""Append CJ-MLK-03 cycle 5 (7 Aug 2026) CVS claims to evidence register."""
import csv, os

REGISTER = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"
HEADER = "claim_id,workstream,claim,source_name,source_type,source_url,source_date,evidence_type,tier,validation_status,confidence_score,authority,traceability,recency,consistency,completeness,issue_gap,owner,action_required,last_reviewed"

# New claims CVS-MLK-344 to CVS-MLK-358
rows = [
    ("CVS-MLK-344","CJ-MLK-03","Hadi Awang (PAS president) confirmed preliminary BN-PN Melaka seat-negotiation discussions have BEGUN (7 Aug 2026); talks at early stage with further negotiations expected in coming weeks; negotiations factor in BN winning 0 parliamentary seats in Melaka; DUN Melaka not yet dissolved.","Malay Mail + Utusan Malaysia","L4","https://www.malaymail.com/news/malaysia/2026/08/07/perikatan-and-bn-negotiations-for-melaka-hadi-says-goal-remains-to-unite-and-save-the-malays/230516","2026-08-07","News report (EN+BM corroboration)","T2","Verified","8","1","2","2","2","1","Dual-source EN+BM corroboration; advances PIR-05 from anticipated to commenced","CJ-MLK-03","None","2026-08-07"),
    ("CVS-MLK-345","CJ-MLK-03","Hadi Awang declared Bersatu is no longer part of PN after Bersatu announced plans to form new coalition (7 Aug 2026); argued PN constitution auto-removes any party joining/establishing another alliance; no formal announcement needed.","Malay Mail + FMT","L4","https://www.malaymail.com/news/malaysia/2026/08/07/hadi-says-bersatu-no-longer-part-of-perikatan-after-plans-for-new-coalition/230500","2026-08-07","News report (dual-source)","T2","Verified","7","1","2","2","2","0","DISPUTED by Bersatu (CVS-MLK-357); paradigm shift for PIR-05/09","CJ-MLK-03","Monitor for Bersatu response","2026-08-07"),
    ("CVS-MLK-346","CJ-MLK-03","Muhyiddin Yassin (Bersatu president) announced Bersatu will form new coalition after NS polls (17 Jul 2026); new coalition = Ikatan Prihatin Rakyat (IPR) with Ibrahim Ali's Putra + P Ramasamy's Urimai; called PN 'toxic' under PAS leadership; will contest next GE.","FMT + NST","L4","https://www.freemalaysiatoday.com/category/nation/2026/07/17/bersatu-to-form-new-coalition-after-negeri-sembilan-polls","2026-07-17","News report","T2","Verified","8","1","2","1","2","1","Foundational event for 7 Aug Hadi declaration; Bersatu de facto exit operationalized at NS","CJ-MLK-03","None","2026-08-07"),
    ("CVS-MLK-347","CJ-MLK-03","Bersatu contested NS election separately under its OWN banner (24 candidates) NOT as part of PN's 11 seats; BN contested 25/36 NS seats; PAS-Bersatu cooperation ended June 2026; PAS refused to campaign for Bersatu in Johor (11 Jul); Bersatu wiped out in Johor.","FMT","L4","https://www.freemalaysiatoday.com/category/nation/2026/07/17/bersatu-to-form-new-coalition-after-negeri-sembilan-polls","2026-07-17","News report","T2","Verified","8","1","2","1","2","1","De facto PN split already operational at NS; Bersatu went solo","CJ-MLK-03","None","2026-08-07"),
    ("CVS-MLK-348","CJ-MLK-03","Hadi dismissed Zahid's 'defend 21 Melaka seats' statement as a 'personal statement' (kenyataan peribadi); both coalitions still negotiating; Melaka cooperation model may differ from NS; BN's 0 parliamentary seats in Melaka is explicit negotiation leverage.","Utusan Malaysia (BM)","L4","https://www.utusan.com.my/nasional/2026/08/prn-melaka-bn-pn-sudah-buat-rundingan-awal/","2026-08-07","News report (BM)","T2","Verified","7","1","2","2","2","1","PAS/PN rejects BN's 21-seat claim as a negotiating position not agreement","CJ-MLK-03","None","2026-08-07"),
    ("CVS-MLK-349","CJ-MLK-03","PAS ended political cooperation with Bersatu in June 2026; both remained PN components amid worsening ties; PAS refused to help Bersatu's Johor campaign (11 Jul) though both contested under PN banner; PAS led PN in BN electoral pact post-Johor.","FMT + Malay Mail","L4","https://www.freemalaysiatoday.com/category/nation/2026/08/07/hadi-claims-bersatu-already-out-of-pn","2026-06-xx","News report","T2","Verified","7","1","2","1","2","1","Timeline context for PN split; exact PAS-Bersatu break date in June unconfirmed","CJ-MLK-03","Confirm exact June break date","2026-08-07"),
    ("CVS-MLK-350","CJ-MLK-03","Adly Zahari (Amanah VP ex-CM Melaka) stated Amanah is the party MOST affected by racial politics; Amanah lost ALL 9 NS seats including Klawang; retained only Simpang Jeram (Johor); Amanah is the Malay-majority Islamic-messaging party within PH.","Utusan Malaysia + Berita Harian","L4","https://www.utusan.com.my/nasional/2026/08/amanah-paling-terkesan-akibat-politik-perkauman-adly-zahari/","2026-08-02","News report (dual BM)","T2","Verified","8","1","2","2","2","1","Dual-source corroboration; quantifies Amanah devastation (0/9 NS)","CJ-MLK-03","None","2026-08-07"),
    ("CVS-MLK-351","CJ-MLK-03","Adly Zahari said Amanah MAY CHANGE strategy for PRN Melaka; strategy to be decided in PH meeting first; internal debate on prior campaign approach (too aggressive vs too defensive); post-mortem of PRN ongoing.","Utusan Malaysia","L4","https://www.utusan.com.my/nasional/2026/08/amanah-paling-terkesan-akibat-politik-perkauman-adly-zahari/","2026-08-02","News report (BM)","T2","Verified","7","1","2","2","2","1","Adly signals potential strategy pivot subject to PH 8 Aug meeting","CJ-MLK-03","Capture 8 Aug meeting outcome","2026-08-07"),
    ("CVS-MLK-352","CJ-MLK-03","Adly Zahari said Amanah open to cooperation with Islam-based AND Malay-based parties sharing value-based politics; cited PH-MUDA cooperation precedent from previous PRN Melaka; PH remains Amanah's tunjang (anchor); focus on coalition-building not just seat addition.","Berita Harian","L4","https://www.bharian.com.my/berita/nasional/2026/08/1596795/amanah-nilai-prestasi-dalam-2-prn-tumpu-perkukuh-kerjasama-politik","2026-08-02","News report (BM)","T2","Verified","7","1","2","2","2","1","PH-MUDA precedent signals openness to small-party pacts; refines CVS-MLK-191","CJ-MLK-03","Monitor PH-BERSAMA accommodation","2026-08-07"),
    ("CVS-MLK-353","CJ-MLK-03","PH 8 Aug 2026 meeting was PRE-SCHEDULED before Johor/NS elections (not emergency reaction); to review PRN losses frame PRU16/PRN strategy enhance social media; Chow Kon Yeow (PH Penang chairman) flagged investor-confidence concerns from political realignment.","BuletinTV3 + Harian Metro","L4","https://www.buletintv3.my/politik/ph-mesyuarat-8-ogos-teliti-punca-kekalahan-rangka-strategi-baharu/","2026-08-xx","News report (dual BM)","T2","Verified","7","1","2","2","2","1","Pre-scheduled = planned checkpoint not panic; outcome pending (meeting ~9hrs away)","CJ-MLK-03","Capture 8 Aug meeting outcome","2026-08-07"),
    ("CVS-MLK-354","CJ-MLK-03","BERSAMA (Rafizi Ramli's party) ground operations launch confirmed 8 Aug 2026 at Sentral Melaka Hotel Jalan Tun Sri Lanang; two programs; candidate announcement timing still uncertain (June sources said 'early August').","X/Twitter @rafiziramli","L5","https://x.com/rafiziramli/status/2084852002908217801","2026-08-07","Social media (L5)","T2","Partially Verified","5","0","1","2","2","0","L5 social source; candidate list NOT yet confirmed; vote-splitter variable","CJ-MLK-03","Capture candidate announcement","2026-08-07"),
    ("CVS-MLK-355","CJ-MLK-03","Bersatu disciplinary board (10 Mar 2026) suspended Mas Ermieyati 2 terms effective immediately; STRIPPED OF ALL PARTY POSITIONS (incl Srikandi chief); BANNED from statements on behalf of party; basis Fasal 9.1.4; she will NOT appeal.","Astro Awani","L4","https://www.astroawani.com/berita-politik/bersatu-gantung-ronald-kiandee-mas-ermieyati-dua-penggal","2026-03-10","News report (Bernama)","T2","Verified","8","1","2","1","2","1","RESOLVES T5 CVS-MLK-186/258/210: 'all positions' explicitly includes Srikandi chief; title VACATED 10 Mar 2026","CJ-MLK-03","None — T5 resolved","2026-08-07"),
    ("CVS-MLK-356","CJ-MLK-03","[ASSESSMENT] If Hadi's Bersatu-out-of-PN claim holds the PN negotiating with BN for Melaka = PAS-led PN (PAS + Gerakan + possibly WAWASAN) excluding Bersatu; Bersatu/IPR becomes a 4th electoral force; Melaka could see BN vs PAS-PN vs PH vs Bersatu-IPR vs BERSAMA = maximized vote fragmentation benefiting BN.","CJ-MLK-03 analytical synthesis","L5","N/A — analytical","2026-08-07","Analytical assessment","T3","Inferred","6","0","2","2","2","0","Analytical; contingent on Hadi's disputed claim being upheld","CJ-MLK-03","Human review — analytical","2026-08-07"),
    ("CVS-MLK-357","CJ-MLK-03","[DISPUTED] Bersatu's membership status in PN is contested: Hadi (PAS) says Bersatu automatically out per PN constitution after forming IPR coalition; Bersatu/Muhyiddin says still in PN claiming constitution requires consensus to remove any member.","Malay Mail + FMT","L4","https://www.malaymail.com/news/malaysia/2026/08/07/hadi-says-bersatu-no-longer-part-of-perikatan-after-plans-for-new-coalition/230500","2026-08-07","News report (disputed positions)","T5","Disputed","5","1","2","2","2","0","Genuine T5 conflict on coalition membership; constitutional interpretation disputed","CJ-MLK-03","Escalation — resolve via PN official statement","2026-08-07"),
    ("CVS-MLK-358","CJ-MLK-03","[ASSESSMENT] Reconciliation of PAS 16-seat claim (Zulkifli Apr) vs PN 'equal share' ~14 (FMT analyst 6 Aug): with Bersatu out of PN these are PAS-led-PN demands — PAS claiming 16 (>half of 28) is the operational seat demand; the 'equal share ~14' was analyst framing; the 2021 irony is PN's only 2 Melaka seats were Bersatu-won (Sungai Udang Bemban) while PAS won 0 — now PAS claims 16 and Bersatu is excluded.","CJ-MLK-03 analytical synthesis","L5","N/A — analytical","2026-08-07","Analytical assessment","T3","Inferred","6","0","2","2","1","0","Reconciles Auto-Approved Suggestion #1; 2021 irony noted; Bemban now WAWASAN (Yadzil)","CJ-MLK-03","Human review — analytical","2026-08-07"),
]

with open(REGISTER, "a", newline="") as f:
    writer = csv.writer(f)
    for r in rows:
        writer.writerow(r)

print(f"Appended {len(rows)} claims (CVS-MLK-344 to CVS-MLK-358)")
print("Tier distribution:")
from collections import Counter
tiers = Counter(r[8] for r in rows)
for t, c in sorted(tiers.items()):
    print(f"  {t}: {c}")
print("Score distribution:")
scores = Counter(r[10] for r in rows)
for s, c in sorted(scores.items(), reverse=True):
    print(f"  {s}: {c}")
