#!/usr/bin/env python3
"""CJ-MLK-04 Cycle 5 — Append CVS Evidence Register entries."""

import csv
import os

REGISTER = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"

NEW_ENTRIES = [
    {
        "claim_id": "CVS-MLK-364",
        "workstream": "CJ-MLK-04",
        "claim": "Bakri Jamaluddin (MP Tangga Batu) was appointed as Independent Non-Executive Director of TDM Berhad (plantation company owned by Terengganu State Government) on March 27, 2024",
        "source_name": "Harakah Daily",
        "source_type": "News Portal (L4)",
        "source_url": "https://harakahdaily.net/tag/melaka/",
        "source_date": "2024-03-27",
        "evidence_type": "Affiliation",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "7",
        "authority": "1",
        "traceability": "2",
        "recency": "0",
        "consistency": "1",
        "completeness": "1",
        "issue_gap": "Verify TDM Berhad annual report for current board status; appointment predates PRN cycle",
        "owner": "CJ-MLK-04",
        "action_required": "Verify TDM Berhad Bursa Malaysia filing for current directorship status",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-365",
        "workstream": "CJ-MLK-04",
        "claim": "PAS is open to receiving individual BERSATU leaders who wish to join the party (reported Aug 7, 2026)",
        "source_name": "Harakah Daily sidebar",
        "source_type": "News Portal (L4)",
        "source_url": "https://harakahdaily.net/tag/melaka/",
        "source_date": "2026-08-07",
        "evidence_type": "Position",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "5",
        "authority": "1",
        "traceability": "1",
        "recency": "2",
        "consistency": "1",
        "completeness": "0",
        "issue_gap": "Headline-level only; full article not accessible (404 on Astro Awani URL)",
        "owner": "CJ-MLK-04",
        "action_required": "Extract full article for complete PAS statement on receiving BERSATU leaders",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-366",
        "workstream": "CJ-MLK-04",
        "claim": "PAS seen as society's main choice in Alor Gajah, Melaka due to current national political developments (Jan 6, 2026)",
        "source_name": "Harakah Daily",
        "source_type": "News Portal (L4)",
        "source_url": "https://harakahdaily.net/tag/melaka/",
        "source_date": "2026-01-06",
        "evidence_type": "Grassroots Sentiment",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "6",
        "authority": "1",
        "traceability": "2",
        "recency": "1",
        "consistency": "1",
        "completeness": "1",
        "issue_gap": "Source is PAS Kawasan (local chapter) — party-internal perspective",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-367",
        "workstream": "CJ-MLK-04",
        "claim": "PAS Melaka DHPP (Dewan Himpunan Pendukong PAS) committee formed for 2025-2027 term at Melaka State DHPP Convention with increased enthusiasm",
        "source_name": "Harakah Daily",
        "source_type": "News Portal (L4)",
        "source_url": "https://harakahdaily.net/tag/melaka/",
        "source_date": "2025-06-19",
        "evidence_type": "Organizational",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "6",
        "authority": "1",
        "traceability": "2",
        "recency": "1",
        "consistency": "1",
        "completeness": "1",
        "issue_gap": "Summary-level only; full convention details not accessible",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-368",
        "workstream": "CJ-MLK-04",
        "claim": "MyTrees@Melaka system has logged 70,753 tree inventory records; system developed in 2017; announced by CM Ab Rauf Yusoh on 7 Aug 2026",
        "source_name": "Melaka Hari Ini",
        "source_type": "News Portal (L4)",
        "source_url": "https://www.melakahariini.my",
        "source_date": "2026-08-07",
        "evidence_type": "Policy Initiative",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "7",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "1",
        "completeness": "1",
        "issue_gap": "Verify if MyTrees falls under Helmy's EXCO portfolio or CM's office directly",
        "owner": "CJ-MLK-04",
        "action_required": "Verify portfolio attribution — Helmy's Science/Tech/Digital Communication or CM's office",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-369",
        "workstream": "CJ-MLK-04",
        "claim": "RM1 million approved by Melaka State Government for water supply restoration at Kem Terendak and Kem Sungai Udang; announced by Senior Exco Rais Yasin on 1 Aug 2026",
        "source_name": "Melaka Hari Ini",
        "source_type": "News Portal (L4)",
        "source_url": "https://www.melakahariini.my",
        "source_date": "2026-08-01",
        "evidence_type": "Constituency Activity",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "7",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "1",
        "completeness": "1",
        "issue_gap": "Kem Sungai Udang is in N11 Sungai Udang (BERSATU ADUN) within Bakri's P136 Tangga Batu",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-370",
        "workstream": "CJ-MLK-04",
        "claim": "800 special athletes from 28 DUN constituencies participated in OKU Sports 2026 at Stadium Tun Fatimah Bukit Serindit Duyong on 1 Aug 2026; organized by Exco Kalsom Noordin (N15) not Helmy",
        "source_name": "Melaka Hari Ini",
        "source_type": "News Portal (L4)",
        "source_url": "https://www.melakahariini.my",
        "source_date": "2026-08-01",
        "evidence_type": "Constituency Activity",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "7",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "1",
        "completeness": "1",
        "issue_gap": "Event in Helmy's Duyong constituency but led by another EXCO member",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-371",
        "workstream": "CJ-MLK-04",
        "claim": "Azmin Ali (BERSATU Sec-Gen) disputes Hadi's auto-exit claim citing PN Constitution Clause 7A (only Presidential Council can determine membership); BERSATU to file official complaint with Registrar of Societies (RoS)",
        "source_name": "Astro Awani (Bernama)",
        "source_type": "News Portal (L4)",
        "source_url": "https://www.astroawani.com/berita-politik/abdul-hadi-dakwa-bersatu-terkeluar-pn-azmin-tegaskan-masih-anggota-sah",
        "source_date": "2026-08-07",
        "evidence_type": "Position",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "2",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Adds legal detail (Clause 7A + RoS complaint) to existing CVS-MLK-359 (CJ-MLK-09)",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor for PN Presidential Council meeting or RoS ruling",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-372",
        "workstream": "CJ-MLK-04",
        "claim": "[ASSESSMENT] PAS open to receiving BERSATU leaders = post-break grassroots outreach strategy beyond coalition politics; individual BERSATU members may join PAS at state/local level under Zulkifli's Melaka commissionership",
        "source_name": "CJ-MLK-04 analyst",
        "source_type": "Analytical Assessment",
        "source_url": "",
        "source_date": "2026-08-08",
        "evidence_type": "Assessment",
        "tier": "T3",
        "validation_status": "Inferred",
        "confidence_score": "6",
        "authority": "1",
        "traceability": "1",
        "recency": "2",
        "consistency": "1",
        "completeness": "0",
        "issue_gap": "Based on headline-level source; full PAS statement not accessible",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor for BERSATU-to-PAS defections at Melaka state/local level",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-373",
        "workstream": "CJ-MLK-04",
        "claim": "[ASSESSMENT] MyTrees@Melaka digital initiative falls under Helmy's Digital Communication portfolio scope but was announced by CM Ab Rauf not Helmy; consistent with Cycle 4 assessment that Helmy's portfolio is more administrative than policy-driving",
        "source_name": "CJ-MLK-04 analyst",
        "source_type": "Analytical Assessment",
        "source_url": "",
        "source_date": "2026-08-08",
        "evidence_type": "Assessment",
        "tier": "T3",
        "validation_status": "Inferred",
        "confidence_score": "6",
        "authority": "1",
        "traceability": "1",
        "recency": "2",
        "consistency": "2",
        "completeness": "0",
        "issue_gap": "Portfolio attribution not confirmed — may be CM's office or JPN initiative",
        "owner": "CJ-MLK-04",
        "action_required": "Verify if Helmy has driven any science/tech/digital policy initiative independently",
        "last_reviewed": "2026-08-08",
    },
]

def append_entries():
    with open(REGISTER, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "claim_id", "workstream", "claim", "source_name", "source_type",
            "source_url", "source_date", "evidence_type", "tier",
            "validation_status", "confidence_score", "authority",
            "traceability", "recency", "consistency", "completeness",
            "issue_gap", "owner", "action_required", "last_reviewed"
        ])
        for entry in NEW_ENTRIES:
            writer.writerow(entry)
    print(f"Appended {len(NEW_ENTRIES)} entries (CVS-MLK-364 to CVS-MLK-373)")

if __name__ == "__main__":
    append_entries()
