#!/usr/bin/env python3
"""Append CJ-MLK-09 cycle 17:37 new CVS claims to the evidence register."""
import csv
from pathlib import Path

REG = Path("/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv")

# Field order (20 fields):
# claim_id,workstream,claim,source_name,source_type,source_url,source_date,
# evidence_type,tier,validation_status,confidence_score,authority,traceability,
# recency,consistency,completeness,issue_gap,owner,action_required,last_reviewed
rows = [
    {
        "claim_id": "CVS-MLK-433",
        "workstream": "MLK",
        "claim": "BN chairman Ahmad Zahid Hamidi stated BN intends to defend all 21 DUN seats it won in Melaka at the coming PRN; ambition voiced by CM Ab Rauf Yusoh; BN remains open to talks with any party and central leadership to be consulted before any final deal",
        "source_name": "Astro Awani",
        "source_type": "L4 News",
        "source_url": "https://www.astroawani.com/berita-politik/bn-mahu-pertahan-21-kerusi-dun-di-melaka",
        "source_date": "2026-08-06",
        "evidence_type": "Coalition Statement",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "0",
        "issue_gap": "Full article extracted; statement is Zahid reporting Ab Rauf intent; final seat-deal terms not yet agreed",
        "owner": "CJ-MLK-09",
        "action_required": "None",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-434",
        "workstream": "MLK",
        "claim": "AMK (PKR Youth) Exco Dzul Hilmi Zainol accused Datuk Seri Rafizi Ramli's new party (dubbed Parti Kancil) of planning to contest PRN Melaka allegedly to help UMNO split PH votes",
        "source_name": "Astro Awani",
        "source_type": "L4 News",
        "source_url": "https://www.astroawani.com/berita-politik/rafizi-hipokrit-masuk-prn-melaka-bantu-umno-pecah-undi-ph-amk",
        "source_date": "2026-08-06",
        "evidence_type": "Intra-coalition Friction",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "6",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "1", "completeness": "0",
        "issue_gap": "Headline/snippet level; full body not extracted; naming Parti Kancil vs prior-cycle BERSAMA to reconcile",
        "owner": "CJ-MLK-09",
        "action_required": "Corroboration; reconcile party name",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-435",
        "workstream": "MLK",
        "claim": "CM Ab Rauf Yusoh hinted PRN Melaka can be held bila-bila masa (anytime) following Johor and NS successes; no fixed date to dissolve DUN",
        "source_name": "Berita Harian",
        "source_type": "L4 News",
        "source_url": "https://www.bharian.com.my/berita/nasional/2026/08/1596823/rauf-beri-bayangan-prn-melaka-bila-bila-masa",
        "source_date": "2026-08-08",
        "evidence_type": "PRN Timing Signal",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "6",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "1", "completeness": "0",
        "issue_gap": "Snippet level; full body not extracted; term-end framing conflicts with other sources (see CVS-MLK-439)",
        "owner": "CJ-MLK-09",
        "action_required": "Reconcile term-end date",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-436",
        "workstream": "MLK",
        "claim": "Political analyst (Sinar Harian) expects Ab Rauf to seek audience with Yang di-Pertua Negeri in the near term to dissolve DUN and projects PRN Melaka in early September 2026",
        "source_name": "Sinar Harian (PRU @ Sinar)",
        "source_type": "L4 News",
        "source_url": "https://pru.sinarharian.com.my/info-berita/23015/prn-melaka-awal-september",
        "source_date": "2026-08-08",
        "evidence_type": "Analyst Projection",
        "tier": "T4",
        "validation_status": "Inferred",
        "confidence_score": "5",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "1", "completeness": "0",
        "issue_gap": "Projection not fact; analyst identity not fully confirmed from snippet",
        "owner": "CJ-MLK-09",
        "action_required": "Human review - projection",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-437",
        "workstream": "MLK",
        "claim": "Utusan analyst report (Dr Nur Ayuni Mohd Isa, UPM) frames Melaka as testing ground for BN-PN cooperation; identifies three competing seat-allocation formulas (incumbent / latest-PRU15-results / winability); notes Hadi Awang signaled Melaka formula may differ from Johor/NS; no official BN-PN talks for PRN Melaka as of 7 Aug 2026",
        "source_name": "Utusan Malaysia",
        "source_type": "L4 News",
        "source_url": "https://www.utusan.com.my/nasional/2026/08/melaka-bakal-menjadi-medan-ujian-sebenar-ketahanan-kerjasama-bn-pn-penganalisis/",
        "source_date": "2026-08-05",
        "evidence_type": "Analyst Analysis",
        "tier": "T3",
        "validation_status": "Inferred",
        "confidence_score": "7",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "2", "completeness": "0",
        "issue_gap": "Analytical content (T3); full article extracted; corroborates PAS-still-negotiating thread",
        "owner": "CJ-MLK-09",
        "action_required": "Human review - analytical",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-438",
        "workstream": "MLK",
        "claim": "[DISPUTED] BN DUN seat count in Melaka reported as 20 of 28 (Utusan analyst piece, 5 Aug) vs 21 of 28 (Zahid Hamidi defend-21 statement, 6 Aug; 14 July ADUN-Lantikan vote recorded 21 BN supporting)",
        "source_name": "Utusan Malaysia (20) vs Astro Awani/Wikipedia (21)",
        "source_type": "L4 News",
        "source_url": "https://www.utusan.com.my/nasional/2026/08/melaka-bakal-menjadi-medan-ujian-sebenar-ketahanan-kerjasama-bn-pn-penganalisis/",
        "source_date": "2026-08-05",
        "evidence_type": "Seat Composition Discrepancy",
        "tier": "T5",
        "validation_status": "Disputed",
        "confidence_score": "5",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "0", "completeness": "0",
        "issue_gap": "Sources conflict on BN seat count (20 vs 21); possible single-seat erosion or reporting error; no named BN ADUN defection corroborated",
        "owner": "CJ-MLK-09",
        "action_required": "Escalation - reconcile 20 vs 21; identify any defected/vacant BN seat",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-439",
        "workstream": "MLK",
        "claim": "[DISPUTED] Melaka state assembly term-end date reported variously as 30 Nov 2026 (Sinar Harian, Ab Rauf) / 31 Dec 2026 (Berita Harian, Ab Rauf) / on or before 25 Feb 2027 (Wikipedia, constitutional limit)",
        "source_name": "Sinar Harian vs Berita Harian vs Wikipedia",
        "source_type": "L4 News",
        "source_url": "https://www.sinarharian.com.my/article/771755/berita/politik/tarikh-prn-melaka-belum-diputuskan---ab-rauf",
        "source_date": "2026-08-08",
        "evidence_type": "Term-End Date Discrepancy",
        "tier": "T5",
        "validation_status": "Disputed",
        "confidence_score": "5",
        "authority": "1", "traceability": "2", "recency": "2", "consistency": "0", "completeness": "0",
        "issue_gap": "Three different term-end dates across sources attributed to same official; affects PRN outer-bound timing",
        "owner": "CJ-MLK-09",
        "action_required": "Escalation - reconcile via official state constitution/gazette (L1)",
        "last_reviewed": "2026-08-08",
    },
    {
        "claim_id": "CVS-MLK-440",
        "workstream": "MLK",
        "claim": "[ASSESSMENT] PRN Melaka timing is consolidating toward an early-September 2026 window; combined with PAS overlap on 4 of 5 marginal seats and no finalized BN-PN deal, multi-cornered-fight risk for the marginals (esp. N26 Serkam) is consolidating rather than receding",
        "source_name": "Analytical synthesis (CJ-MLK-09)",
        "source_type": "L5 AI-derived",
        "source_url": "",
        "source_date": "2026-08-08",
        "evidence_type": "Analytical",
        "tier": "T3",
        "validation_status": "Inferred",
        "confidence_score": "5",
        "authority": "0", "traceability": "2", "recency": "2", "consistency": "1", "completeness": "0",
        "issue_gap": "Analytical; contingent on timing signals (Ab Rauf hint + analyst projection) holding",
        "owner": "CJ-MLK-09",
        "action_required": "Human review - analytical",
        "last_reviewed": "2026-08-08",
    },
]

fieldnames = [
    "claim_id", "workstream", "claim", "source_name", "source_type", "source_url",
    "source_date", "evidence_type", "tier", "validation_status", "confidence_score",
    "authority", "traceability", "recency", "consistency", "completeness",
    "issue_gap", "owner", "action_required", "last_reviewed",
]

# Append (preserve existing header; do not rewrite whole file)
with REG.open("a", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
    for r in rows:
        writer.writerow(r)

print(f"Appended {len(rows)} rows.")
print("Last claim_id:", rows[-1]["claim_id"])
