#!/usr/bin/env python3
"""Append CJ-MLK-04 Cycle 3 claims to CVS Evidence Register."""
import csv
import os

REGISTER = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"

# New claims from Cycle 3 (CVS-MLK-140 to CVS-MLK-151)
claims = [
    {
        "claim_id": "CVS-MLK-140",
        "workstream": "MLK",
        "claim": "Shamsul Iskandar was formally dropped (digugurkan) from PKR Melaka MPN Chairman effective 15 Dec 2025 by PKR Political Bureau following his 4 Dec 2025 corruption charges; Adam Adli took over; Hang Tuah Jaya branch chairmanship retained",
        "source_name": "Malaysiakini",
        "source_type": "L4 News",
        "source_url": "https://www.malaysiakini.com/news/763504",
        "source_date": "2025-12-16",
        "evidence_type": "Party Discipline",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "2",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Triple-corroborated (Malaysiakini+TheVibes+MalayMail); human review can upgrade to T1",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-141",
        "workstream": "MLK",
        "claim": "Adam Adli Abdul Halim appointed Acting PKR Melaka MPN Chairman effective 15 Dec 2025 serving until further notice; Shamsul accepted decision via Facebook 17 Dec 2025",
        "source_name": "The Vibes",
        "source_type": "L4 News",
        "source_url": "https://www.thevibes.com/articles/news/117063/shamsul-iskandar-accepts-pkr-decision-as-adam-adli-appointed-acting-melaka-chairman",
        "source_date": "2025-12-17",
        "evidence_type": "Party Appointment",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "2",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Corroborated by Malaysiakini + Malay Mail",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-142",
        "workstream": "MLK",
        "claim": "Adam Adli remained Acting PKR Melaka MPN Chairman as of 15 Jul 2026 handling PH withdrawal crisis; title now Deputy Higher Education Minister (changed from Deputy Youth & Sports in Dec 2025)",
        "source_name": "Malay Mail",
        "source_type": "L4 News",
        "source_url": "https://www.malaymail.com/news/malaysia/2026/07/15/melaka-pkr-urges-calm-seeks-consensus-on-nominated-assemblymen-issue/227620",
        "source_date": "2026-07-15",
        "evidence_type": "Status Confirmation",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Portfolio change (Youth to Higher Education) needs independent corroboration",
        "owner": "CJ-MLK-04",
        "action_required": "Confirm Adam Adli ministerial portfolio change",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-143",
        "workstream": "MLK",
        "claim": "Shamsul Iskandar is officially listed as a former (archived) MP for P137 Hang Tuah Jaya Melaka in the Parliament of Malaysia official archive (L1 source)",
        "source_name": "Parlimen.gov.my",
        "source_type": "L1 Official",
        "source_url": "https://www.parlimen.gov.my/arkib-ahli.html?uweb=dr&id=3661&vol=14&arkib=yes",
        "source_date": "2026-05-14",
        "evidence_type": "Official Record",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "2",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "L1 official source; human review can upgrade to T1",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-144",
        "workstream": "MLK",
        "claim": "Bakri Jamaluddin (PN-Tangga Batu) delivered a Dewan Rakyat speech during the debate on the royal address on 21 Jan 2026 advocating for Baba Nyonya and Chetty communities to be recognized as national unity icons",
        "source_name": "The Star",
        "source_type": "L4 News",
        "source_url": "https://www.thestar.com.my/news/nation/2026/01/21/highlight-baba-nyonya-chetty-communities-as-national-unity-icon-urges-mp",
        "source_date": "2026-01-21",
        "evidence_type": "Parliamentary Activity",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "9",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "2",
        "issue_gap": "Corroborated by TikTok + MYMP",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-145",
        "workstream": "MLK",
        "claim": "Bakri Jamaluddin has submitted 117 parliamentary questions presented 21 motions and attended 89 of 90 parliamentary sessions (98.9%) as MP for Tangga Batu per MYMP updated Nov 2025",
        "source_name": "MYMP.org.my",
        "source_type": "L4 Civic Monitor",
        "source_url": "https://mymp.org.my/p/bakri-jamaluddin",
        "source_date": "2025-11-24",
        "evidence_type": "Parliamentary Record",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Sourced from parliamentary records via civic platform",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-146",
        "workstream": "MLK",
        "claim": "Bakri Jamaluddin (PAS) appointed Secretary (Setiausaha) of PN Melaka on 14 May 2026 as 4th senior role alongside MP Tangga Batu + Deputy PAS Commissioner + PAS Central Committee member",
        "source_name": "Free Malaysia Today",
        "source_type": "L4 News",
        "source_url": "https://www.freemalaysiatoday.com/category/nation/2026/05/14/radzi-jidin-appointed-melaka-pn-chairman",
        "source_date": "2026-05-14",
        "evidence_type": "Coalition Appointment",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "0",
        "issue_gap": "Single source; consistent with role profile",
        "owner": "CJ-MLK-04",
        "action_required": "Corroboration",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-147",
        "workstream": "MLK",
        "claim": "Zulkifli Ismail (PAS Commissioner Melaka) appointed Deputy Chairman of PN Melaka on 14 May 2026 alongside 3 other deputy chairmen; meeting centered on operational readiness for state election",
        "source_name": "Free Malaysia Today",
        "source_type": "L4 News",
        "source_url": "https://www.freemalaysiatoday.com/category/nation/2026/05/14/radzi-jidin-appointed-melaka-pn-chairman",
        "source_date": "2026-05-14",
        "evidence_type": "Coalition Appointment",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Corroborated by Wikipedia MS PRN page",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-148",
        "workstream": "MLK",
        "claim": "Zulkifli Ismail holds role as Timbalan Ketua Dewan Ulamak PAS Pusat (Deputy Head of PAS Central Ulama Council) in addition to PAS Commissioner MP Jasin and Deputy Chairman PN Melaka",
        "source_name": "Facebook @UstazZulkifliIsmail (official page)",
        "source_type": "L5 Social Media (official)",
        "source_url": "https://www.facebook.com/UstazZulkifliIsmail/",
        "source_date": "2026-08-06",
        "evidence_type": "Party Position",
        "tier": "T2",
        "validation_status": "Partially Verified",
        "confidence_score": "7",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "0",
        "issue_gap": "From official Facebook bio; needs PAS official website corroboration",
        "owner": "CJ-MLK-04",
        "action_required": "Corroboration from PAS official source",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-149",
        "workstream": "MLK",
        "claim": "PN Melaka leadership structure institutionalizes PAS-Bersatu coordination: Chairman Radzi Jidin (BERSATU) + Deputy Zulkifli (PAS) + Secretary Bakri (PAS) + Election Director Ali Mohamad (BERSATU ex-UMNO); appointed 14 May 2026",
        "source_name": "Free Malaysia Today",
        "source_type": "L4 News",
        "source_url": "https://www.freemalaysiatoday.com/category/nation/2026/05/14/radzi-jidin-appointed-melaka-pn-chairman",
        "source_date": "2026-05-14",
        "evidence_type": "Coalition Structure",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "Structure disrupted by PAS-Bersatu break 8-9 Jun 2026 per CJ-MLK-03",
        "owner": "CJ-MLK-04",
        "action_required": "Monitor post-break PN Melaka status",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-150",
        "workstream": "MLK",
        "claim": "Bakri Jamaluddin campaigned for PN candidate PM Kumar in N.11 Lobak Negeri Sembilan PRN on 31 Jul 2026 demonstrating cross-state coalition mobilization; operates as opposition MP without government constituency allocation",
        "source_name": "Harakah Daily",
        "source_type": "L4 News (PAS-affiliated)",
        "source_url": "https://harakahdaily.net/2026/07/31/bakri-yakin-pm-kumar-semakin-aktif-bantu-rakyat/",
        "source_date": "2026-07-31",
        "evidence_type": "Campaign Activity",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "None",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
    {
        "claim_id": "CVS-MLK-151",
        "workstream": "MLK",
        "claim": "Melaka DUN composition mid-2026: BN 20 (UMNO 17/MCA 2/MIC 1) PH 5 (DAP 4/AMANAH 1) PN 3 (PAS 1/BERSATU 1/WAWASAN 1); PRN Melaka 2026 expected with 28 seats and 15-seat majority threshold",
        "source_name": "Wikipedia Bahasa Melayu",
        "source_type": "L4 Encyclopedia",
        "source_url": "https://ms.wikipedia.org/wiki/Pilihan_raya_negeri_Melaka_2026",
        "source_date": "2026-08-06",
        "evidence_type": "Electoral Data",
        "tier": "T2",
        "validation_status": "Verified",
        "confidence_score": "8",
        "authority": "1",
        "traceability": "2",
        "recency": "2",
        "consistency": "2",
        "completeness": "1",
        "issue_gap": "WAWASAN reclassification of N24 Bemban; corroborated by Cycle 2 DUN page",
        "owner": "CJ-MLK-04",
        "action_required": "None",
        "last_reviewed": "2026-08-06",
    },
]

# Read existing file to preserve header and detect line ending
with open(REGISTER, "r", encoding="utf-8") as f:
    content = f.read()

# Detect line ending
line_ending = "\r\n" if "\r\n" in content else "\n"

# Append new rows
fieldnames = list(claims[0].keys())

with open(REGISTER, "a", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, lineterminator=line_ending)
    for row in claims:
        writer.writerow(row)

print(f"Appended {len(claims)} claims (CVS-MLK-140 to CVS-MLK-151) to evidence register.")
print(f"Line ending used: {repr(line_ending)}")
