#!/usr/bin/env python3
"""Append new CVS claims (CVS-MLK-180 to 199) to the evidence register."""
import csv, os

REGISTER = "/home/p62operator/.openclaw/workspace-mlk/03-VERIFICATION/CVS-EVIDENCE-REGISTER.csv"

# 20 new claims from CJ-MLK-03 cycle 3 (2026-08-06)
# Fields: claim_id,workstream,claim,source_name,source_type,source_url,source_date,evidence_type,tier,validation_status,confidence_score,authority,traceability,recency,consistency,completeness,issue_gap,owner,action_required,last_reviewed
rows = [
["CVS-MLK-180","MLK","BN Chairman Ahmad Zahid Hamidi stated 1 Aug 2026 the BN-PN blue wave momentum from Johor and NS (25 combined seats two-thirds majority) will spread to PRN Melaka",  "Utusan Malaysia","L4 News","https://www.utusan.com.my/nasional/2026/08/gelombang-biru-dan-biru-pekat-diteruskan-ke-prn-melaka-ahmad-zahid/","2026-08-01","Coalition Posture","T2","Partially Verified","8","1","2","2","2","1","Corroborated by Kosmo 1 Aug + BERNAMA BN Plus 2 Aug","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-181","MLK","[ASSESSMENT] PAS 16-seat claim overlaps multiple BN-held seats (Tanjung Bidara Merlimau Paya Rumput Ayer Molek Pengkalan Batu Duyong) indicating contest-vs-BN fallback or negotiating baseline","Analytical interpretation (CJ-MLK-03)","L5 AI-derived","https://www.utusan.com.my/nasional/2026/04/pas-umum-bertanding-16-kerusi-prn-melaka/","2026-08-06","Analytical","T3","Inferred","6","1","1","2","2","0","Analytical synthesis not fact","CJ-MLK-03","Human review","2026-08-06"],
["CVS-MLK-182","MLK","PAS Melaka (Commissioner Zulkifli Ismail) announced 29 Apr 2026 it will contest 16 of 28 DUN seats in PRN Melaka listing seats incl BN-held Tanjung Bidara (CM) Merlimau (Akmal) Paya Rumput Ayer Molek Pengkalan Batu Duyong","Utusan Malaysia","L4 News","https://www.utusan.com.my/nasional/2026/04/pas-umum-bertanding-16-kerusi-prn-melaka/","2026-04-29","Seat Allocation","T2","Verified","9","1","2","1","2","2","Sole concrete PN seat-claim; predates NS BN-PN momentum","CJ-MLK-03","Monitor whether 16-seat claim holds post-NS","2026-08-06"],
["CVS-MLK-183","MLK","Mas Ermieyati Samsudin resigned as Bersatu Masjid Tanah division chief on 19 Feb 2026 with 39 committee members dissolving the division citing loss of confidence in President Muhyiddin Yassin","NST + MalaysiaGazette","L4 News (2 outlets)","https://www.nst.com.my/news/nation/2026/02/1381159/mas-ermieyati-quits-bersatu-masjid-tanah-chief-amid-party-turmoil","2026-02-19","Party Discipline","T2","Verified","9","1","2","1","2","2","Precursor to 10 Mar suspension (CVS-MLK-121)","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-184","MLK","Mas Ermieyati Samsudin attended the WAWASAN party launch (Reset Convention Tanah Merah Kelantan) on 13 Jun 2026 described as aligned with Hamzah","The Star + FMT","L4 News (2 outlets)","https://www.thestar.com.my/news/nation/2026/06/14/new-party-on-the-block","2026-06-13","Political Alignment","T2","Verified","9","1","2","1","2","2","Confirms orbit not formal membership","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-185","MLK","Mas Ermieyati is NOT listed in WAWASAN official leadership structure (Chairman Rais Yatim President Hamzah etc.) as of party registration 6 Jul 2026","Wikipedia BM","L5 Encyclopedia","https://ms.wikipedia.org/wiki/Parti_Wawasan_Negara","2026-07-06","Party Status","T2","Partially Verified","7","1","2","2","2","0","Monitor for formal defection","CJ-MLK-03","Corroborate via WAWASAN official roster/ROS","2026-08-06"],
["CVS-MLK-186","MLK","[DISPUTED] FMT (13 Jun 2026) refers to Mas Ermieyati as Bersatu Wanita chief despite her 10 Mar 2026 BERSATU membership suspension stripping all party positions (CVS-MLK-121)","FMT vs BERNAMA/Bharian","L4 News (conflicting)","https://www.freemalaysiatoday.com/category/nation/2026/06/13/hamzah-unveils-new-party-wawasan","2026-06-13","Title Dispute","T5","Disputed","4","1","2","1","0","0","Sources conflict on Srikandi title status post-suspension","CJ-MLK-03","Escalation - verify via BERSATU official","2026-08-06"],
["CVS-MLK-187","MLK","[ASSESSMENT] Mas Ermieyati is orbiting WAWASAN (attended launch aligned with Hamzah broke with Bersatu Feb-Mar 2026) but has NOT formally defected/joined as of 6 Aug 2026","Analytical synthesis (CJ-MLK-03)","L5 AI-derived","","2026-08-06","Analytical","T3","Inferred","6","1","1","2","2","0","Analytical not fact","CJ-MLK-03","Human review - monitor defection","2026-08-06"],
["CVS-MLK-188","MLK","WAWASAN (Parti Wawasan Negara) is a PN component party since 2026 founded 13 Jun 2026 by Hamzah Zainudin via takeover of PCM registered 6 Jul 2026 with 120000 members","Wikipedia BM","L5 Encyclopedia","https://ms.wikipedia.org/wiki/Parti_Wawasan_Negara","2026-07-06","Party Identity","T2","Partially Verified","7","1","2","2","2","0","Corroborate via ROS registry","CJ-MLK-03","Corroboration via ROS/WAWASAN official","2026-08-06"],
["CVS-MLK-189","MLK","WAWASAN holds N24 Bemban in Melaka via Mohd Yadzil Yaakub who moved from BERSATU to WAWASAN making WAWASAN one of PN 3 Melaka DUN seats","Wikipedia BM + CVS-MLK-044/151","L5 Encyclopedia","https://ms.wikipedia.org/wiki/Parti_Wawasan_Negara","2026-07-06","Seat Affiliation","T2","Verified","8","1","2","2","2","1","Resolves Bemban WAWASAN reclassification (CVS-MLK-151)","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-190","MLK","Mas Ermieyati Samsudin is NOT listed in WAWASAN official leadership structure as of party registration 6 Jul 2026","Wikipedia BM","L5 Encyclopedia","https://ms.wikipedia.org/wiki/Parti_Wawasan_Negara","2026-07-06","Party Status","T2","Partially Verified","7","1","2","2","2","0","Monitor for formal defection announcement","CJ-MLK-03","Monitor","2026-08-06"],
["CVS-MLK-191","MLK","Amanah VP Adly Zahari stated 2 Aug 2026 (post-NS losses) PH remains cornerstone of Amanah struggle but room to expand cooperation with parties championing values-based politics including Islamic and Malay-based platforms","NST","L4 News","https://www.nst.com.my/news/nation/2026/08/1502720/amanah-eyes-wider-political-cooperation-after-negri-poll-losses","2026-08-02","Coalition Positioning","T2","Verified","8","1","2","2","2","1","Corroborates CVS-MLK-126 with greater granularity","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-192","MLK","Amanah failed to win any of the 9 seats it contested in NS PRN 2026 including Klawang which it previously held (now WAWASAN Danni Rais)","NST","L4 News","https://www.nst.com.my/news/nation/2026/08/1502720/amanah-eyes-wider-political-cooperation-after-negri-poll-losses","2026-08-02","Electoral Result","T2","Partially Verified","7","1","2","2","2","0","Corroborate 0/9 vs SPR official NS results","CJ-MLK-03","Corroborate via SPR","2026-08-06"],
["CVS-MLK-193","MLK","CM Ab Rauf Yusoh announced 17 Jul 2026 Melaka will not fill PH-vacated positions (Exco councillors JPKK) due to limited time left in term","theSun/BERNAMA","L4 News","https://thesun.my/news/malaysia-news/politics/melaka-wont-fill-ph-vacancies-after-coalition-exits-state-government/","2026-07-17","Governance","T2","Verified","8","1","2","1","2","2","Post-withdrawal governance","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-194","MLK","Ab Rauf Yusoh stated 17 Jul 2026 he has not yet seen a BN-PN arrangement in Melaka similar to NS but did not rule out better BN-PN understanding in the state","theSun/BERNAMA","L4 News","https://thesun.my/news/malaysia-news/politics/melaka-wont-fill-ph-vacancies-after-coalition-exits-state-government/","2026-07-17","Coalition Posture","T2","Verified","8","1","2","1","2","2","Consistent with BN Plus formula","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-195","MLK","PH Melaka (5 ADUN) confirmed final withdrawal from state government on 16 Jul 2026 at Amanah HQ Bukit Katil rejecting appointed-ADUN amendment; PBT/JPKK to leave by 31 Jul; signatories Adly Adam Adli Khoo Ashraf Mukhlis","Utusan Malaysia","L4 News","https://www.utusan.com.my/nasional/2026/07/ph-melaka-muktamad-keluar-kerajaan-negeri/","2026-07-16","Coalition Event","T2","Verified","9","1","2","1","2","2","Corroborates CVS-MLK-138/165; adds meeting location + transition","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-196","MLK","PH will hold meeting 8 Aug 2026 (pre-scheduled) to review Johor/NS losses and frame new strategy for PRU16 and upcoming PRN including Melaka with social media intensification","Harian Metro","L4 News","https://www.hmetro.com.my/mutakhir/2026/08/1392994/ph-mesyuarat-8-ogos-teliti-kekalahan-prn-rangka-strategi-baharu","2026-08-02","Coalition Strategy","T2","Verified","9","1","2","2","2","2","Corroborated by Utusan/Bharian/BuletinTV3; outcome pending","CJ-MLK-03","Capture 8 Aug outcome next cycle","2026-08-06"],
["CVS-MLK-197","MLK","190+ former UMNO members rejoined UMNO Masjid Tanah division on 18 May 2026 via Zahid Rumah Bangsa initiative at Ab Rauf residence mobilized as PRN Melaka election machinery","Astro Awani/BERNAMA","L2 National News Agency","https://www.astroawani.com/berita-politik/lebih-190-bekas-ahli-kembali-sertai-umno-bahagian-masjid-tanah","2026-05-18","Ground Mobilization","T2","Verified","9","2","2","1","2","1","BN reclaiming Masjid Tanah post-BERSATU collapse","CJ-MLK-03","None","2026-08-06"],
["CVS-MLK-198","MLK","PAS President Abdul Hadi Awang stated PN-BN cooperation in Melaka will not necessarily follow Johor/NS model signaling more complex seat negotiations and flexible unity-spirit approach","Sinar Harian (analisis)","L4 News","https://www.sinarharian.com.my/article/790685/suara-sinar/analisis-sinar/melaka-medan-uji-keserasian-pn-bn","2026-08-04","Coalition Posture","T2","Partially Verified","7","1","2","2","2","0","Corroborate via primary Hadi statement","CJ-MLK-03","Corroboration via primary source","2026-08-06"],
["CVS-MLK-199","MLK","[ASSESSMENT] PRN Melaka is critical test of whether BN-PN is durable pact or electoral convenience; BN 21/28 DUN dominance gives less incentive to concede seats to PN creating tension benefiting PH if unresolved","Analytical interpretation (CJ-MLK-03)","L5 AI-derived","https://www.sinarharian.com.my/article/790685/suara-sinar/analisis-sinar/melaka-medan-uji-keserasian-pn-bn","2026-08-06","Analytical","T3","Inferred","6","1","1","2","2","0","Analytical not fact","CJ-MLK-03","Human review","2026-08-06"],
]

# Append to register (preserve existing content)
with open(REGISTER, "a", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    for row in rows:
        writer.writerow(row)

print(f"Appended {len(rows)} new claims (CVS-MLK-180 to CVS-MLK-199) to evidence register.")

# Verify
with open(REGISTER, "r", encoding="utf-8") as f:
    lines = f.readlines()
print(f"Register now has {len(lines)} lines (incl header).")
